#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AttachToOverlappingTree

#include "Basic.hpp"

#include "AttachToOverlappingTree_classes.hpp"
#include "AttachToOverlappingTree_parameters.hpp"


namespace SDK
{

// Function AttachToOverlappingTree.AttachToOverlappingTree_C.ReceiveExecute
// (Event, Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAttachToOverlappingTree_C::ReceiveExecute(class AActor* OwnerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AttachToOverlappingTree_C", "ReceiveExecute");

	Params::AttachToOverlappingTree_C_ReceiveExecute Parms{};

	Parms.OwnerActor = OwnerActor;

	UObject::ProcessEvent(Func, &Parms);
}

}

