#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_HealAura_Passive

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Buff_HealAura_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_HealAura_Passive.Buff_HealAura_Passive_C
// 0x0010 (0x0D78 - 0x0D68)
class ABuff_HealAura_Passive_C final : public ABuff_HealAura_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Buff_HealAura_Passive_C;            // 0x0D68(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          isCurrentlyHealing;                                // 0x0D70(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Activate_Healing();
	void ExecuteUbergraph_Buff_HealAura_Passive(int32 EntryPoint);
	void HealCharacter(class APrimalCharacter* Character, double Amount);
	void ReceiveBeginPlay();
	void StartHealing();
	void TriggerDelayedHealing();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_HealAura_Passive_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_HealAura_Passive_C")
	}
	static class ABuff_HealAura_Passive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_HealAura_Passive_C>();
	}
};
DUMPER7_ASSERTS_ABuff_HealAura_Passive_C;

}

