#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Galli_Character_BP

#include "Basic.hpp"

#include "Dino_Character_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Galli_Character_BP.Galli_Character_BP_C
// 0x0050 (0x2A60 - 0x2A10)
class AGalli_Character_BP_C final : public ADino_Character_BP_C
{
public:
	class UBP_PrimalWindSourceComponent_Base_C*   BP_PrimalWindSourceComponent_Tail;                 // 0x2A08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PrimalWindSourceComponent_Base_C*   BP_PrimalWindSourceComponent_Tail_Base;            // 0x2A10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PrimalWindSourceComponent_Base_C*   BP_PrimalWindSourceComponent_Head;                 // 0x2A18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PrimalWindSourceComponent_Base_C*   BP_PrimalWindSourceComponent_Neck;                 // 0x2A20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PrimalWindSourceComponent_Base_C*   BP_PrimalWindSourceComponent_Neck_Base;            // 0x2A28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PrimalWindSourceComponent_Base_C*   BP_PrimalWindSourceComponent_Leg_L;                // 0x2A30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PrimalWindSourceComponent_Base_C*   BP_PrimalWindSourceComponent_Leg_R;                // 0x2A38(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PrimalWindSourceComponent_Base_C*   BP_PrimalWindSourceComponent_Body;                 // 0x2A40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNS_DinoFootprint_BP_C*                 NS_DinoFootprint_BP;                               // 0x2A48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UProximitySound_C*                      ProximitySound;                                    // 0x2A50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDinoCharacterStatusComponent_BP_Galli_C* DinoCharacterStatus_BP_Galli_C1;                 // 0x2A58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Galli_Character_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Galli_Character_BP_C")
	}
	static class AGalli_Character_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGalli_Character_BP_C>();
	}
};
DUMPER7_ASSERTS_AGalli_Character_BP_C;

}

