#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SeedHarvestComponent_Fiber

#include "Basic.hpp"

#include "SeedHarvestComponent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SeedHarvestComponent_Fiber.SeedHarvestComponent_Fiber_C
// 0x0000 (0x0228 - 0x0228)
class USeedHarvestComponent_Fiber_C final : public USeedHarvestComponent_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SeedHarvestComponent_Fiber_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SeedHarvestComponent_Fiber_C")
	}
	static class USeedHarvestComponent_Fiber_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USeedHarvestComponent_Fiber_C>();
	}
};
DUMPER7_ASSERTS_USeedHarvestComponent_Fiber_C;

}

