// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "CoreUObject_STRUCTS.h"
#include "SupplyCrateBaseBP_Instantaneous_CLASSES.h"

namespace CG::CoreUObject { class UClass; }
namespace CG::Engine { class UParticleSystemComponent; }
namespace CG::Engine { class UPointLightComponent; }
namespace CG::Engine { class USkeletalMeshComponent; }
namespace CG::PrimalInventoryBP_ArtifactCrate { class UPrimalInventoryBP_ArtifactCrate_C; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::ArtifactCrate_Instantaneous_Alt
{
// BlueprintGeneratedClass /Game/PrimalEarth/Structures/ArtifactCrates/ArtifactCrate_Instantaneous_Alt.ArtifactCrate_Instantaneous_Alt_C
// 0x040(0x1468 - 0x1428)
class AArtifactCrate_Instantaneous_Alt_C : public SupplyCrateBaseBP_Instantaneous::ASupplyCrateBaseBP_Instantaneous_C
{
public:
    Engine::UPointLightComponent*                                        PointLight_1;                       // 0x1428(0x0008) BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash
    PrimalInventoryBP_ArtifactCrate::UPrimalInventoryBP_ArtifactCrate_C* PrimalInventoryBP_ArtifactCrate_C1; // 0x1430(0x0008) BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash
    Engine::USkeletalMeshComponent*                                      SkeletalMesh1;                      // 0x1438(0x0008) BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash
    Engine::UParticleSystemComponent*                                    ParticleSystem1;                    // 0x1440(0x0008) BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash
    CoreUObject::FLinearColor                                            LightColor;                         // 0x1448(0x0010) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    double                                                               LightIntensity;                     // 0x1458(0x0008) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    double                                                               LightAttenuation;                   // 0x1460(0x0008) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

public:
    void UserConstructionScript();
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
