// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"
#include "EPreviewModuleState_ENUMS.h"

namespace CG::ShooterGame { class APrimalStructure; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BunkerModuleData
{
// UserDefinedStruct /Game/LostColony/Structures/TekBunker/Structs/BunkerModuleData.BunkerModuleData
// 0x023
struct FBunkerModuleData
{
public:
    BasicTypes::TArray<uint8_t>              Coordinates_36_74986D924F036827D0B2ACAD0BFDC840;              // 0x0000(0x0010) Edit, BlueprintVisible
    EPreviewModuleState::EPreviewModuleState ModuleState_61_E7962B804604E8535F5421AD15E38F70;              // 0x0010(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t                                  ModuleState_61_E7962B804604E8535F5421AD15E38F70_Padding[0x7]; // 0x0011(0x0007) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    ShooterGame::APrimalStructure*           Terminal_52_5370866B4A31EB93B98ACE82FB8192EE;                 // 0x0018(0x0008) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash
    bool                                     HasTerminal_56_E72EBD1541C51E03EF0C489AC2557407;              // 0x0020(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    bool                                     IsFloorModule_54_B7FF58A74A4DC9F7AA112792D494BAD1;            // 0x0021(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    bool                                     HasModuleBelow_58_12B5843F4A5EA223E9D5718907F91213;           // 0x0022(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
