// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "SlateCore_STRUCTS.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::ChangeCameraModeUI_Widget
{
// 0x03C
// Function /Game/ASA/UI/ChangeCameraMode/ChangeCameraModeUI_Widget.ChangeCameraModeUI_Widget_C.Tick
struct UChangeCameraModeUI_Widget_C_Tick_Params final
{
public:
    SlateCore::FGeometry MyGeometry;  // 0x0000(0x0038) BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor
    float                InDeltaTime; // 0x0038(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/ASA/UI/ChangeCameraMode/ChangeCameraModeUI_Widget.ChangeCameraModeUI_Widget_C.Construct
struct UChangeCameraModeUI_Widget_C_Construct_Params final
{

};

// 0x001
// Function /Game/ASA/UI/ChangeCameraMode/ChangeCameraModeUI_Widget.ChangeCameraModeUI_Widget_C.OnGamepadActiveChangedBP
struct UChangeCameraModeUI_Widget_C_OnGamepadActiveChangedBP_Params final
{
public:
    bool bIsGamepadActive; // 0x0000(0x0001) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x004
// Function /Game/ASA/UI/ChangeCameraMode/ChangeCameraModeUI_Widget.ChangeCameraModeUI_Widget_C.ExecuteUbergraph_ChangeCameraModeUI_Widget
struct UChangeCameraModeUI_Widget_C_ExecuteUbergraph_ChangeCameraModeUI_Widget_Params final
{
public:
    int32_t EntryPoint; // 0x0000(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
