// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_STRUCTS.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::ChaosSolverEngine
{
// 0x001
// Function /Script/ChaosSolverEngine.ChaosSolverActor.SetSolverActive
struct AChaosSolverActor_SetSolverActive_Params final
{
public:
    bool bActive; // 0x0000(0x0001) Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// 0x000
// Function /Script/ChaosSolverEngine.ChaosSolverActor.SetAsCurrentWorldSolver
struct AChaosSolverActor_SetAsCurrentWorldSolver_Params final
{

};

// 0x1C8
// Function /Script/ChaosSolverEngine.ChaosSolverEngineBlueprintLibrary.ConvertPhysicsCollisionToHitResult
struct UChaosSolverEngineBlueprintLibrary_ConvertPhysicsCollisionToHitResult_Params final
{
public:
    FChaosPhysicsCollisionInfo PhysicsCollision; // 0x0000(0x00C0) Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic
    Engine::FHitResult         ReturnValue;      // 0x00C0(0x0108) Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
