// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"
#include "CheatMapJumpInfo_STRUCTS.h"
#include "CoreUObject_STRUCTS.h"
#include "Engine_STRUCTS.h"
#include "ShooterGame_CLASSES.h"

namespace CG::CheatMenu { class UCheatMenu_C; }
namespace CG::CoreUObject { class UClass; }
namespace CG::UMG { class UButton; }
namespace CG::UMG { class UTextBlock; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::CheatMapJumpButton
{
// WidgetBlueprintGeneratedClass /Game/PrimalEarth/UI/CheatMenu/CheatMapJumpButton.CheatMapJumpButton_C
// 0x050(0x3C8 - 0x378)
class UCheatMapJumpButton_C : public ShooterGame::UUI_DebugSpawnMenuEntry
{
public:
    Engine::FPointerToUberGraphFrame UberGraphFrame; // 0x0378(0x0008) ZeroConstructor, Transient, DuplicateTransient
    UMG::UTextBlock*                 ButtonText;     // 0x0380(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    UMG::UButton*                    SpawnButton;    // 0x0388(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    CheatMenu::UCheatMenu_C*         AttachedMenu;   // 0x0390(0x0008) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash
    CoreUObject::FVector             Lat_Long__Z;    // 0x0398(0x0018) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    BasicTypes::FString              Time_Of_Day;    // 0x03B0(0x0010) Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash
    double                           Yaw;            // 0x03C0(0x0008) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

public:
    void SetMapJumpInfo(CheatMapJumpInfo::FCheatMapJumpInfo Info);
    void BndEvt__SpawnButton_K2Node_ComponentBoundEvent_160_OnButtonClickedEvent__DelegateSignature();
    void ExecuteUbergraph_CheatMapJumpButton(int32_t EntryPoint);
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
