// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"
#include "BlendStack_STRUCTS.h"
#include "Chooser_ENUMS.h"
#include "CoreUObject_STRUCTS.h"
#include "Engine_ENUMS.h"
#include "GameplayTags_ENUMS.h"
#include "GameplayTags_STRUCTS.h"

namespace CG::Chooser { class UChooserTable; }
namespace CG::CoreUObject { class UClass; }
namespace CG::CoreUObject { class UObject; }
namespace CG::CoreUObject { class UScriptStruct; }
namespace CG::Engine { class UBlendProfile; }
namespace CG::Engine { class UMirrorDataTable; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Chooser
{
// ScriptStruct /Script/Chooser.AnimCurveOverride
// 0x00C
struct FAnimCurveOverride
{
public:
    BasicTypes::FName CurveName;  // 0x0000(0x0008) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    float             CurveValue; // 0x0008(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ChooserColumnBase
// 0x008
struct FChooserColumnBase
{
public:
    uint8_t FChooserColumnBase_Padding[0x8]; // 0x0000(0x0008) STRUCT PADDING

};

// ScriptStruct /Script/Chooser.ChooserEnumRowData
// 0x008
struct FChooserEnumRowData
{
public:
    EEnumColumnCellValueComparison Comparison;                       // 0x0000(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                        Value;                            // 0x0004(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                        FChooserEnumRowData_Padding[0x3]; // 0x0005(0x0003) MISSED OFFSET (FIX STRUCT SIZE)

};

// ScriptStruct /Script/Chooser.ChooserEvaluationContext
// 0x078
struct FChooserEvaluationContext
{
public:
    uint8_t FChooserEvaluationContext_Padding[0x78]; // 0x0000(0x0078) STRUCT PADDING

};

// ScriptStruct /Script/Chooser.ChooserEvaluationInputObject
// 0x008
struct FChooserEvaluationInputObject
{
public:
    uint8_t FChooserEvaluationInputObject_Padding[0x8]; // 0x0000(0x0008) STRUCT PADDING

};

// ScriptStruct /Script/Chooser.ChooserFloatDistanceRowData
// 0x004
struct FChooserFloatDistanceRowData
{
public:
    float Value; // 0x0000(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ChooserFloatRangeRowData
// 0x00C
struct FChooserFloatRangeRowData
{
public:
    float   min;                                    // 0x0000(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    float   max;                                    // 0x0004(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool    bNoMin;                                 // 0x0008(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool    bNoMax;                                 // 0x0009(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t FChooserFloatRangeRowData_Padding[0x2]; // 0x000A(0x0002) MISSED OFFSET (FIX STRUCT SIZE)

};

// ScriptStruct /Script/Chooser.ChooserMultiEnumRowData
// 0x004
struct FChooserMultiEnumRowData
{
public:
    uint32_t Value; // 0x0000(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ChooserObjectClassRowData
// 0x010
struct FChooserObjectClassRowData
{
public:
    EObjectClassColumnCellValueComparison Comparison;              // 0x0000(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                               Comparison_Padding[0x4]; // 0x0004(0x0004) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    CoreUObject::UClass*                  Value;                   // 0x0008(0x0008) Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ChooserObjectRowData
// 0x030
struct FChooserObjectRowData
{
public:
    EObjectColumnCellValueComparison                 Comparison;              // 0x0000(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                                          Comparison_Padding[0x4]; // 0x0004(0x0004) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    BasicTypes::TSoftObjectPtr<CoreUObject::UObject> Value;                   // 0x0008(0x0028) Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ChooserOutputEnumRowData
// 0x001
struct FChooserOutputEnumRowData
{
public:
    uint8_t Value; // 0x0000(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ChooserOutputObjectRowData
// 0x010
struct FChooserOutputObjectRowData
{
public:
    CoreUObject::FInstancedStruct Value; // 0x0000(0x0010) Edit, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ChooserParameterBase
// 0x008
struct FChooserParameterBase
{
public:
    uint8_t FChooserParameterBase_Padding[0x8]; // 0x0000(0x0008) STRUCT PADDING

};

// ScriptStruct /Script/Chooser.ChooserPropertyBinding
// 0x028
struct FChooserPropertyBinding
{
public:
    BasicTypes::TArray<BasicTypes::FName> PropertyBindingChain;                  // 0x0000(0x0010) ZeroConstructor, NativeAccessSpecifierPublic
    int32_t                               ContextIndex;                          // 0x0010(0x0004) ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool                                  IsBoundToRoot;                         // 0x0014(0x0001) ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                               FChooserPropertyBinding_Padding[0x13]; // 0x0015(0x0013) MISSED OFFSET (FIX STRUCT SIZE)

};

// ScriptStruct /Script/Chooser.ChooserRandomizationContext
// 0x050
struct FChooserRandomizationContext
{
public:
    uint8_t FChooserRandomizationContext_Padding[0x50]; // 0x0000(0x0050) STRUCT PADDING

};

// ScriptStruct /Script/Chooser.ContextObjectTypeBase
// 0x004
struct FContextObjectTypeBase
{
public:
    EContextObjectDirection Direction; // 0x0000(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ObjectChooserBase
// 0x008
struct FObjectChooserBase
{
public:
    uint8_t FObjectChooserBase_Padding[0x8]; // 0x0000(0x0008) STRUCT PADDING

};

// ScriptStruct /Script/Chooser.AnimCurveOverrideList
// 0x018
struct FAnimCurveOverrideList
{
public:
    BasicTypes::TArray<FAnimCurveOverride> Values;                              // 0x0000(0x0010) Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic
    uint32_t                               Hash;                                // 0x0010(0x0004) ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                                FAnimCurveOverrideList_Padding[0x4]; // 0x0014(0x0004) MISSED OFFSET (FIX STRUCT SIZE)

};

// ScriptStruct /Script/Chooser.BoolColumn
// 0x020(0x028 - 0x008)
struct FBoolColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct            InputValue;       // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    BasicTypes::TArray<EBoolColumnCellValue> RowValuesWithAny; // 0x0018(0x0010) Edit, ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.EnumColumnBase
// 0x000(0x008 - 0x008)
struct FEnumColumnBase : public FChooserColumnBase
{

};

// ScriptStruct /Script/Chooser.GameplayTagColumn
// 0x028(0x030 - 0x008)
struct FGameplayTagColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct                           InputValue;                        // 0x0008(0x0010) Edit, NativeAccessSpecifierPublic
    GameplayTags::EGameplayContainerMatchType               TagMatchType;                      // 0x0018(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    EGameplayTagMatchDirection                              TagMatchDirection;                 // 0x0019(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool                                                    bMatchExact;                       // 0x001A(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool                                                    bInvertMatchingLogic;              // 0x001B(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                                                 bInvertMatchingLogic_Padding[0x4]; // 0x001C(0x0004) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    BasicTypes::TArray<GameplayTags::FGameplayTagContainer> RowValues;                         // 0x0020(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.OutputBoolColumn
// 0x028(0x030 - 0x008)
struct FOutputBoolColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct InputValue;                  // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    bool                          bFallbackValue;              // 0x0018(0x0001) ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                       bFallbackValue_Padding[0x7]; // 0x0019(0x0007) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    BasicTypes::TArray<bool>      RowValues;                   // 0x0020(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.OutputFloatColumn
// 0x028(0x030 - 0x008)
struct FOutputFloatColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct InputValue;    // 0x0008(0x0010) Edit, NativeAccessSpecifierPublic
    double                        FallbackValue; // 0x0018(0x0008) ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    BasicTypes::TArray<double>    RowValues;     // 0x0020(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.OutputStructColumn
// 0x030(0x038 - 0x008)
struct FOutputStructColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct                     InputValue;    // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    CoreUObject::FInstancedStruct                     FallbackValue; // 0x0018(0x0010) NativeAccessSpecifierPublic
    BasicTypes::TArray<CoreUObject::FInstancedStruct> RowValues;     // 0x0028(0x0010) Edit, ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.RandomizeColumn
// 0x028(0x030 - 0x008)
struct FRandomizeColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct InputValue;                  // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    float                         RepeatProbabilityMultiplier; // 0x0018(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    float                         EqualCostThreshold;          // 0x001C(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    BasicTypes::TArray<float>     RowValues;                   // 0x0020(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.FloatDistanceColumn
// 0x040(0x048 - 0x008)
struct FFloatDistanceColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct                    InputValue;              // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    double                                           MaxDistance;             // 0x0018(0x0008) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    float                                            CostMultiplier;          // 0x0020(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool                                             bFilterOverMaxDistance;  // 0x0024(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool                                             bWrapInput;              // 0x0025(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                                          bWrapInput_Padding[0x2]; // 0x0026(0x0002) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    double                                           MinValue;                // 0x0028(0x0008) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    double                                           MaxValue;                // 0x0030(0x0008) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    BasicTypes::TArray<FChooserFloatDistanceRowData> RowValues;               // 0x0038(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.FloatRangeColumn
// 0x038(0x040 - 0x008)
struct FFloatRangeColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct                 InputValue;              // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    bool                                          bWrapInput;              // 0x0018(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                                       bWrapInput_Padding[0x7]; // 0x0019(0x0007) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    double                                        MinValue;                // 0x0020(0x0008) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    double                                        MaxValue;                // 0x0028(0x0008) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    BasicTypes::TArray<FChooserFloatRangeRowData> RowValues;               // 0x0030(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.MultiEnumColumn
// 0x020(0x028 - 0x008)
struct FMultiEnumColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct                InputValue; // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    BasicTypes::TArray<FChooserMultiEnumRowData> RowValues;  // 0x0018(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ObjectClassColumn
// 0x020(0x028 - 0x008)
struct FObjectClassColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct                  InputValue; // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    BasicTypes::TArray<FChooserObjectClassRowData> RowValues;  // 0x0018(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ObjectColumn
// 0x020(0x028 - 0x008)
struct FObjectColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct             InputValue; // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    BasicTypes::TArray<FChooserObjectRowData> RowValues;  // 0x0018(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.OutputObjectColumn
// 0x030(0x038 - 0x008)
struct FOutputObjectColumn : public FChooserColumnBase
{
public:
    CoreUObject::FInstancedStruct                   InputValue;    // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    BasicTypes::TArray<FChooserOutputObjectRowData> RowValues;     // 0x0018(0x0010) ZeroConstructor, NativeAccessSpecifierPublic
    FChooserOutputObjectRowData                     FallbackValue; // 0x0028(0x0010) NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ChooserParameterBoolBase
// 0x000(0x008 - 0x008)
struct FChooserParameterBoolBase : public FChooserParameterBase
{

};

// ScriptStruct /Script/Chooser.ChooserParameterEnumBase
// 0x000(0x008 - 0x008)
struct FChooserParameterEnumBase : public FChooserParameterBase
{

};

// ScriptStruct /Script/Chooser.ChooserParameterFloatBase
// 0x000(0x008 - 0x008)
struct FChooserParameterFloatBase : public FChooserParameterBase
{

};

// ScriptStruct /Script/Chooser.ChooserParameterGameplayTagBase
// 0x000(0x008 - 0x008)
struct FChooserParameterGameplayTagBase : public FChooserParameterBase
{

};

// ScriptStruct /Script/Chooser.ChooserParameterObjectBase
// 0x000(0x008 - 0x008)
struct FChooserParameterObjectBase : public FChooserParameterBase
{

};

// ScriptStruct /Script/Chooser.ChooserParameterRandomizeBase
// 0x000(0x008 - 0x008)
struct FChooserParameterRandomizeBase : public FChooserParameterBase
{

};

// ScriptStruct /Script/Chooser.ChooserParameterStructBase
// 0x000(0x008 - 0x008)
struct FChooserParameterStructBase : public FChooserParameterBase
{

};

// ScriptStruct /Script/Chooser.ChooserEnumPropertyBinding
// 0x000(0x028 - 0x028)
struct FChooserEnumPropertyBinding : public FChooserPropertyBinding
{

};

// ScriptStruct /Script/Chooser.ChooserObjectPropertyBinding
// 0x000(0x028 - 0x028)
struct FChooserObjectPropertyBinding : public FChooserPropertyBinding
{

};

// ScriptStruct /Script/Chooser.ChooserStructPropertyBinding
// 0x000(0x028 - 0x028)
struct FChooserStructPropertyBinding : public FChooserPropertyBinding
{

};

// ScriptStruct /Script/Chooser.ContextObjectTypeClass
// 0x00C(0x010 - 0x004)
struct FContextObjectTypeClass : public FContextObjectTypeBase
{
public:
    uint8_t              FContextObjectTypeClass_PrePadding[0x4]; // 0x0004(0x0004) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    CoreUObject::UClass* Class;                                   // 0x0008(0x0008) Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ContextObjectTypeStruct
// 0x00C(0x010 - 0x004)
struct FContextObjectTypeStruct : public FContextObjectTypeBase
{
public:
    uint8_t                     FContextObjectTypeStruct_PrePadding[0x4]; // 0x0004(0x0004) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    CoreUObject::UScriptStruct* Struct;                                   // 0x0008(0x0008) Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.AssetChooser
// 0x008(0x010 - 0x008)
struct FAssetChooser : public FObjectChooserBase
{
public:
    CoreUObject::UObject* Asset; // 0x0008(0x0008) Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ClassChooser
// 0x008(0x010 - 0x008)
struct FClassChooser : public FObjectChooserBase
{
public:
    CoreUObject::UClass* Class; // 0x0008(0x0008) Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.EvaluateChooser
// 0x008(0x010 - 0x008)
struct FEvaluateChooser : public FObjectChooserBase
{
public:
    UChooserTable* Chooser; // 0x0008(0x0008) Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.NestedChooser
// 0x008(0x010 - 0x008)
struct FNestedChooser : public FObjectChooserBase
{
public:
    UChooserTable* Chooser; // 0x0008(0x0008) ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.SoftAssetChooser
// 0x028(0x030 - 0x008)
struct FSoftAssetChooser : public FObjectChooserBase
{
public:
    BasicTypes::TSoftObjectPtr<CoreUObject::UObject> Asset; // 0x0008(0x0028) Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ChooserPlayerSettings
// 0x040
struct FChooserPlayerSettings
{
public:
    bool                      bMirror;                             // 0x0000(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                   bMirror_Padding[0x3];                // 0x0001(0x0003) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    float                     StartTime;                           // 0x0004(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool                      bForceLooping;                       // 0x0008(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                   bForceLooping_Padding[0x3];          // 0x0009(0x0003) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    float                     PlaybackRate;                        // 0x000C(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    FAnimCurveOverrideList    CurveOverrides;                      // 0x0010(0x0018) Edit, BlueprintVisible, NativeAccessSpecifierPublic
    float                     BlendTime;                           // 0x0028(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                   BlendTime_Padding[0x4];              // 0x002C(0x0004) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    Engine::UBlendProfile*    BlendProfile;                        // 0x0030(0x0008) Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
    Engine::EAlphaBlendOption BlendOption;                         // 0x0038(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool                      bUseInertialBlend;                   // 0x0039(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                   FChooserPlayerSettings_Padding[0x6]; // 0x003A(0x0006) MISSED OFFSET (FIX STRUCT SIZE)

};

// ScriptStruct /Script/Chooser.EnumColumn
// 0x020(0x028 - 0x008)
struct FEnumColumn : public FEnumColumnBase
{
public:
    CoreUObject::FInstancedStruct           InputValue; // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    BasicTypes::TArray<FChooserEnumRowData> RowValues;  // 0x0018(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.OutputEnumColumn
// 0x028(0x030 - 0x008)
struct FOutputEnumColumn : public FEnumColumnBase
{
public:
    CoreUObject::FInstancedStruct                 InputValue;                 // 0x0008(0x0010) Edit, NoClear, NativeAccessSpecifierPublic
    FChooserOutputEnumRowData                     FallbackValue;              // 0x0018(0x0001) NoDestructor, NativeAccessSpecifierPublic
    uint8_t                                       FallbackValue_Padding[0x7]; // 0x0019(0x0007) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    BasicTypes::TArray<FChooserOutputEnumRowData> RowValues;                  // 0x0020(0x0010) ZeroConstructor, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.BoolContextProperty
// 0x038(0x040 - 0x008)
struct FBoolContextProperty : public FChooserParameterBoolBase
{
public:
    BasicTypes::TArray<BasicTypes::FName> PropertyBindingChain; // 0x0008(0x0010) ZeroConstructor, Deprecated, NativeAccessSpecifierPublic
    FChooserPropertyBinding               Binding;              // 0x0018(0x0028) Edit, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.FloatContextProperty
// 0x038(0x040 - 0x008)
struct FFloatContextProperty : public FChooserParameterFloatBase
{
public:
    BasicTypes::TArray<BasicTypes::FName> PropertyBindingChain; // 0x0008(0x0010) ZeroConstructor, Deprecated, NativeAccessSpecifierPublic
    FChooserPropertyBinding               Binding;              // 0x0018(0x0028) Edit, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.GameplayTagContextProperty
// 0x038(0x040 - 0x008)
struct FGameplayTagContextProperty : public FChooserParameterGameplayTagBase
{
public:
    BasicTypes::TArray<BasicTypes::FName> PropertyBindingChain; // 0x0008(0x0010) ZeroConstructor, Deprecated, NativeAccessSpecifierPublic
    FChooserPropertyBinding               Binding;              // 0x0018(0x0028) Edit, NoClear, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.RandomizeContextProperty
// 0x028(0x030 - 0x008)
struct FRandomizeContextProperty : public FChooserParameterRandomizeBase
{
public:
    FChooserPropertyBinding Binding; // 0x0008(0x0028) Edit, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.EnumContextProperty
// 0x038(0x040 - 0x008)
struct FEnumContextProperty : public FChooserParameterEnumBase
{
public:
    BasicTypes::TArray<BasicTypes::FName> PropertyBindingChain; // 0x0008(0x0010) ZeroConstructor, Deprecated, NativeAccessSpecifierPublic
    FChooserEnumPropertyBinding           Binding;              // 0x0018(0x0028) Edit, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.ObjectContextProperty
// 0x028(0x030 - 0x008)
struct FObjectContextProperty : public FChooserParameterObjectBase
{
public:
    FChooserObjectPropertyBinding Binding; // 0x0008(0x0028) Edit, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.StructContextProperty
// 0x028(0x030 - 0x008)
struct FStructContextProperty : public FChooserParameterStructBase
{
public:
    FChooserStructPropertyBinding Binding; // 0x0008(0x0028) Edit, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/Chooser.AnimNode_ChooserPlayer
// 0x188(0x248 - 0x0C0)
struct FAnimNode_ChooserPlayer : public BlendStack::FAnimNode_BlendStack_Standalone
{
public:
    uint8_t                                           FAnimNode_ChooserPlayer_PrePadding[0x20]; // 0x00C0(0x0020) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    EChooserEvaluationFrequency                       EvaluationFrequency;                      // 0x00E0(0x0004) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                                           EvaluationFrequency_Padding[0x4];         // 0x00E4(0x0004) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    CoreUObject::FInstancedStruct                     Chooser;                                  // 0x00E8(0x0010) Edit, NativeAccessSpecifierPublic
    Engine::UMirrorDataTable*                         MirrorDataTable;                          // 0x00F8(0x0008) Edit, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
    float                                             BlendSpaceX;                              // 0x0100(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    float                                             BlendSpaceY;                              // 0x0104(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                                           BlendSpaceY_Padding[0x8];                 // 0x0108(0x0008) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    FChooserPlayerSettings                            DefaultSettings;                          // 0x0110(0x0040) Edit, NativeAccessSpecifierPublic
    BasicTypes::TArray<CoreUObject::FInstancedStruct> ChooserContextDefinition;                 // 0x0150(0x0010) ZeroConstructor, NativeAccessSpecifierPublic
    bool                                              bStartFromMatchingPose;                   // 0x0160(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t                                           FAnimNode_ChooserPlayer_Padding[0xE7];    // 0x0161(0x00E7) MISSED OFFSET (FIX STRUCT SIZE)

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
