// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "Dino_Character_BP_CLASSES.h"

namespace CG::BP_PrimalWindSourceComponent_Base { class UBP_PrimalWindSourceComponent_Base_C; }
namespace CG::CoreUObject { class UClass; }
namespace CG::DinoCharacterStatusComponent_BP_Coel { class UDinoCharacterStatusComponent_BP_Coel_C; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Coel_Character_BP
{
// BlueprintGeneratedClass /Game/PrimalEarth/Dinos/Coelacanth/Coel_Character_BP.Coel_Character_BP_C
// 0x018(0x2A20 - 0x2A08)
class ACoel_Character_BP_C : public Dino_Character_BP::ADino_Character_BP_C
{
public:
    BP_PrimalWindSourceComponent_Base::UBP_PrimalWindSourceComponent_Base_C*       BP_PrimalWindSourceComponent_Tail; // 0x2A08(0x0008) BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash
    BP_PrimalWindSourceComponent_Base::UBP_PrimalWindSourceComponent_Base_C*       BP_PrimalWindSourceComponent_Body; // 0x2A10(0x0008) BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash
    DinoCharacterStatusComponent_BP_Coel::UDinoCharacterStatusComponent_BP_Coel_C* DinoCharacterStatus_BP_Coel_C1;    // 0x2A18(0x0008) BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash

public:
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
