// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"

namespace CG::CoreUObject { class UObject; }
namespace CG::Engine { class AGameModeBase; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::ConfigFunctionsASA
{
// 0x050
// Function /Game/ASA/Dinos/Ceratosaurus/ASACeratoScripts/ConfigFunctionsASA.ConfigFunctionsASA_C.AACerato GetConfig - Array
struct UConfigFunctionsASA_C_AACerato_GetConfig___Array_Params final
{
public:
    Engine::AGameModeBase*                  GM;             // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    BasicTypes::FString                     Name;           // 0x0008(0x0010) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
    CoreUObject::UObject*                   __WorldContext; // 0x0018(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    BasicTypes::TArray<int32_t>             AsInt;          // 0x0020(0x0010) Parm, OutParm
    BasicTypes::TArray<double>              AsFloat;        // 0x0030(0x0010) Parm, OutParm
    BasicTypes::TArray<BasicTypes::FString> AsString;       // 0x0040(0x0010) Parm, OutParm

};

// 0x040
// Function /Game/ASA/Dinos/Ceratosaurus/ASACeratoScripts/ConfigFunctionsASA.ConfigFunctionsASA_C.AACerato GetConfig - Float
struct UConfigFunctionsASA_C_AACerato_GetConfig___Float_Params final
{
public:
    Engine::AGameModeBase* GM;             // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    BasicTypes::FString    Name;           // 0x0008(0x0010) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
    double                 Default;        // 0x0018(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    double                 min;            // 0x0020(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    double                 max;            // 0x0028(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    CoreUObject::UObject*  __WorldContext; // 0x0030(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    double                 Value;          // 0x0038(0x0008) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x030
// Function /Game/ASA/Dinos/Ceratosaurus/ASACeratoScripts/ConfigFunctionsASA.ConfigFunctionsASA_C.AACerato GetConfig - String
struct UConfigFunctionsASA_C_AACerato_GetConfig___String_Params final
{
public:
    Engine::AGameModeBase* GM;             // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    BasicTypes::FString    Name;           // 0x0008(0x0010) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
    CoreUObject::UObject*  __WorldContext; // 0x0018(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    BasicTypes::FString    Value;          // 0x0020(0x0010) Parm, OutParm, ZeroConstructor, HasGetValueTypeHash

};

// 0x029
// Function /Game/ASA/Dinos/Ceratosaurus/ASACeratoScripts/ConfigFunctionsASA.ConfigFunctionsASA_C.AACerato GetConfig - Bool
struct UConfigFunctionsASA_C_AACerato_GetConfig___Bool_Params final
{
public:
    Engine::AGameModeBase* GM;                    // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    BasicTypes::FString    Name;                  // 0x0008(0x0010) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
    bool                   Default;               // 0x0018(0x0001) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t                UnknownData_0000[0x7]; // 0x0019(0x0007)
    CoreUObject::UObject*  __WorldContext;        // 0x0020(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    bool                   Value;                 // 0x0028(0x0001) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x034
// Function /Game/ASA/Dinos/Ceratosaurus/ASACeratoScripts/ConfigFunctionsASA.ConfigFunctionsASA_C.AACerato GetConfig - Int
struct UConfigFunctionsASA_C_AACerato_GetConfig___Int_Params final
{
public:
    Engine::AGameModeBase* GM;                    // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    BasicTypes::FString    Name;                  // 0x0008(0x0010) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
    int32_t                Default;               // 0x0018(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    int32_t                min;                   // 0x001C(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    int32_t                max;                   // 0x0020(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t                UnknownData_0001[0x4]; // 0x0024(0x0004)
    CoreUObject::UObject*  __WorldContext;        // 0x0028(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    int32_t                Value;                 // 0x0030(0x0004) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
