// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "CoreUObject_STRUCTS.h"
#include "Engine_STRUCTS.h"
#include "ShooterGame_CLASSES.h"

namespace CG::CoreUObject { class UClass; }
namespace CG::UMG { class UButton; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::ConsoleCommandButton
{
// WidgetBlueprintGeneratedClass /Game/PrimalEarth/UI/Inventory/ConsoleCommandButton.ConsoleCommandButton_C
// 0x030(0x800 - 0x7D0)
class UConsoleCommandButton_C : public ShooterGame::UConsoleCommandButtonWidget
{
public:
    Engine::FPointerToUberGraphFrame UberGraphFrame;        // 0x07D0(0x0008) ZeroConstructor, Transient, DuplicateTransient
    UMG::UButton*                    Button;                // 0x07D8(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    CoreUObject::FLinearColor        UnSelectedColorBG;     // 0x07E0(0x0010) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    CoreUObject::FLinearColor        UnSelectedPairColorBG; // 0x07F0(0x0010) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash

public:
    void Construct();
    void ExecuteUbergraph_ConsoleCommandButton(int32_t EntryPoint);
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
