// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "DinoEntry_Andrewsarchus_CLASSES.h"

namespace CG::CoreUObject { class UClass; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::DinoEntry_Fjordhawk
{
// BlueprintGeneratedClass /Game/Fjordur/CoreBlueprints/DinoEntries/DinoEntry_Fjordhawk.DinoEntry_Fjordhawk_C
// 0x000(0x080 - 0x080)
class UDinoEntry_Fjordhawk_C : public DinoEntry_Andrewsarchus::UDinoEntry_Andrewsarchus_C
{
public:
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
