// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "AIModule_STRUCTS.h"
#include "Engine_STRUCTS.h"
#include "ShooterGame_CLASSES.h"

namespace CG::CoreUObject { class UClass; }
namespace CG::GameplayTasks { class UGameplayTasksComponent; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Dino_AIController_BP
{
// BlueprintGeneratedClass /Game/PrimalEarth/CoreAI/Dino_AIController_BP.Dino_AIController_BP_C
// 0x038(0xA58 - 0xA20)
class ADino_AIController_BP_C : public ShooterGame::APrimalDinoAIController
{
public:
    Engine::FPointerToUberGraphFrame        UberGraphFrame; // 0x0A20(0x0008) ZeroConstructor, Transient, DuplicateTransient
    GameplayTasks::UGameplayTasksComponent* GameplayTasks;  // 0x0A28(0x0008) BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash
    AIModule::FBlackboardKeySelector        NavKey;         // 0x0A30(0x0028) Edit, BlueprintVisible

public:
    void ReceiveBeginPlay();
    void ExecuteUbergraph_Dino_AIController_BP(int32_t EntryPoint);
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
