// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>

namespace CG::ShooterGame { class APrimalDinoCharacter; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Dolphin_AIController_BP
{
// 0x009
// Function /Game/PrimalEarth/Dinos/Dolphin/Dolphin_AIController_BP.Dolphin_AIController_BP_C.BPShouldNotifyAnyNeighbor
struct ADolphin_AIController_BP_C_BPShouldNotifyAnyNeighbor_Params final
{
public:
    ShooterGame::APrimalDinoCharacter* neighbor;    // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    bool                               ReturnValue; // 0x0008(0x0001) Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
