// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "DroppedItemGenericLowQuality_CLASSES.h"
#include "Engine_ENUMS.h"
#include "Engine_STRUCTS.h"

namespace CG::CoreUObject { class UClass; }
namespace CG::Engine { class UTimelineComponent; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::DroppedItemGenericLowQuality_Poop
{
// BlueprintGeneratedClass /Game/PrimalEarth/Test/DroppedItemGenericLowQuality_Poop.DroppedItemGenericLowQuality_Poop_C
// 0x028(0x920 - 0x8F8)
class ADroppedItemGenericLowQuality_Poop_C : public DroppedItemGenericLowQuality::ADroppedItemGenericLowQuality_C
{
public:
    Engine::FPointerToUberGraphFrame UberGraphFrame;                                                      // 0x08F8(0x0008) ZeroConstructor, Transient, DuplicateTransient
    float                            Timeline_0_rest_7BA50238424811B699D735A56AAD2D5C;                    // 0x0900(0x0004) ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    float                            Timeline_0_Jiggle_Jiggle_7BA50238424811B699D735A56AAD2D5C;           // 0x0904(0x0004) ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    Engine::ETimelineDirection       Timeline_0__Direction_7BA50238424811B699D735A56AAD2D5C;              // 0x0908(0x0001) ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t                          Timeline_0__Direction_7BA50238424811B699D735A56AAD2D5C_Padding[0x7]; // 0x0909(0x0007) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    Engine::UTimelineComponent*      Timeline_1;                                                          // 0x0910(0x0008) BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash
    double                           Poop_Scale;                                                          // 0x0918(0x0008) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash

public:
    void Timeline_0__FinishedFunc();
    void Timeline_0__UpdateFunc();
    void BPDroppedItemImpacted(const Engine::FHitResult& impactHitInfo);
    void ExecuteUbergraph_DroppedItemGenericLowQuality_Poop(int32_t EntryPoint);
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
