// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "AIModule_CLASSES.h"
#include "Engine_STRUCTS.h"

namespace CG::CoreUObject { class UClass; }
namespace CG::Engine { class AActor; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::IsFlyingBool
{
// BlueprintGeneratedClass /Game/PrimalEarth/CoreAI/IsFlyingBool.IsFlyingBool_C
// 0x008(0x0A8 - 0x0A0)
class UIsFlyingBool_C : public AIModule::UBTDecorator_BlueprintBase
{
public:
    Engine::FPointerToUberGraphFrame UberGraphFrame; // 0x00A0(0x0008) ZeroConstructor, Transient, DuplicateTransient

public:
    void ReceiveConditionCheck(Engine::AActor* OwnerActor);
    void ExecuteUbergraph_IsFlyingBool(int32_t EntryPoint);
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
