// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"
#include "CoreUObject_STRUCTS.h"
#include "SlateCore_STRUCTS.h"
#include "UMG_STRUCTS.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::MapMarkWidget_ASA
{
// 0x130
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.OnPreviewKeyDown
struct UMapMarkWidget_ASA_C_OnPreviewKeyDown_Params final
{
public:
    SlateCore::FGeometry MyGeometry;  // 0x0000(0x0038) BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor
    SlateCore::FKeyEvent InKeyEvent;  // 0x0038(0x0040) BlueprintVisible, BlueprintReadOnly, Parm
    UMG::FEventReply     ReturnValue; // 0x0078(0x00B8) Parm, OutParm, ReturnParm

};

// 0x002
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.Handle Clicking Track Entry
struct UMapMarkWidget_ASA_C_Handle_Clicking_Track_Entry_Params final
{
public:
    bool success;            // 0x0000(0x0001) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    bool click_was_to_track; // 0x0001(0x0001) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x002
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.Handle Clicking Death Marks
struct UMapMarkWidget_ASA_C_Handle_Clicking_Death_Marks_Params final
{
public:
    bool success;            // 0x0000(0x0001) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    bool click_was_to_track; // 0x0001(0x0001) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x168
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.OnPreviewMouseButtonDown
struct UMapMarkWidget_ASA_C_OnPreviewMouseButtonDown_Params final
{
public:
    SlateCore::FGeometry     MyGeometry;  // 0x0000(0x0038) BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor
    SlateCore::FPointerEvent MouseEvent;  // 0x0038(0x0078) BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
    UMG::FEventReply         ReturnValue; // 0x00B0(0x00B8) Parm, OutParm, ReturnParm

};

// 0x008
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.SetProgressPercent
struct UMapMarkWidget_ASA_C_SetProgressPercent_Params final
{
public:
    double Percent; // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x001
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.IsTracking
struct UMapMarkWidget_ASA_C_IsTracking_Params final
{
public:
    bool ReturnValue; // 0x0000(0x0001) Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.Init
struct UMapMarkWidget_ASA_C_Init_Params final
{

};

// 0x001
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.CanTrackMark
struct UMapMarkWidget_ASA_C_CanTrackMark_Params final
{
public:
    bool Can; // 0x0000(0x0001) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.UpdateVisualStyle
struct UMapMarkWidget_ASA_C_UpdateVisualStyle_Params final
{

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.SetTrackStyle
struct UMapMarkWidget_ASA_C_SetTrackStyle_Params final
{

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.SetNormalStyle
struct UMapMarkWidget_ASA_C_SetNormalStyle_Params final
{

};

// 0x020
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.SetTextAndBG
struct UMapMarkWidget_ASA_C_SetTextAndBG_Params final
{
public:
    BasicTypes::FString       NewText; // 0x0000(0x0010) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
    CoreUObject::FLinearColor BGColor; // 0x0010(0x0010) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.SetHoverStyle
struct UMapMarkWidget_ASA_C_SetHoverStyle_Params final
{

};

// 0x001
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.PreConstruct
struct UMapMarkWidget_ASA_C_PreConstruct_Params final
{
public:
    bool IsDesignTime; // 0x0000(0x0001) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.RefreshConstruct
struct UMapMarkWidget_ASA_C_RefreshConstruct_Params final
{

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.BndEvt__MapMarkWidget_ASA_MainButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
struct UMapMarkWidget_ASA_C_BndEvt__MapMarkWidget_ASA_MainButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature_Params final
{

};

// 0x008
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.UpdateTextSize
struct UMapMarkWidget_ASA_C_UpdateTextSize_Params final
{
public:
    double Scale; // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.BndEvt__MapMarkWidget_ASA_MainButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
struct UMapMarkWidget_ASA_C_BndEvt__MapMarkWidget_ASA_MainButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature_Params final
{

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.BndEvt__MapMarkWidget_ASA_MainButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
struct UMapMarkWidget_ASA_C_BndEvt__MapMarkWidget_ASA_MainButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature_Params final
{

};

// 0x000
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.Construct
struct UMapMarkWidget_ASA_C_Construct_Params final
{

};

// 0x004
// Function /Game/ASA/Minimap/Core/UI/MapMarkWidget_ASA.MapMarkWidget_ASA_C.ExecuteUbergraph_MapMarkWidget_ASA
struct UMapMarkWidget_ASA_C_ExecuteUbergraph_MapMarkWidget_ASA_Params final
{
public:
    int32_t EntryPoint; // 0x0000(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
