// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"
#include "CoreUObject_CLASSES.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::MoschopsTamingFoodList
{
// BlueprintGeneratedClass /Game/PrimalEarth/Dinos/Moschops/MoschopsTamingDinoSettings/MoschopsTamingFoodList.MoschopsTamingFoodList_C
// 0x010(0x038 - 0x028)
class UMoschopsTamingFoodList_C : public CoreUObject::UObject
{
public:
    BasicTypes::TArray<CoreUObject::UClass*> TamingFoodsList; // 0x0028(0x0010) Edit, BlueprintVisible, DisableEditOnInstance

public:
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
