// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::MRMesh
{
// ScriptStruct /Script/MRMesh.MRMeshConfiguration
// 0x001
struct FMRMeshConfiguration
{
public:
    uint8_t FMRMeshConfiguration_Padding[0x1]; // 0x0000(0x0001) STRUCT PADDING

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
