// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"

namespace CG::CoreUObject { class UObject; }
namespace CG::Engine { class UTexture2D; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::OptionSelector_Widget
{
// 0x000
// Function /Game/ASA/UI/OptionSelector_Widget.OptionSelector_Widget_C.BndEvt__OptionSelector_Widget_CustomButton_HUB_ASA_C_40_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
struct UOptionSelector_Widget_C_BndEvt__OptionSelector_Widget_CustomButton_HUB_ASA_C_40_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature_Params final
{

};

// 0x028
// Function /Game/ASA/UI/OptionSelector_Widget.OptionSelector_Widget_C.InitOption
struct UOptionSelector_Widget_C_InitOption_Params final
{
public:
    Engine::UTexture2D*   Icon;                  // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    bool                  IsToggled;             // 0x0008(0x0001) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t               UnknownData_0000[0x7]; // 0x0009(0x0007)
    BasicTypes::FText     InText;                // 0x0010(0x0010) BlueprintVisible, BlueprintReadOnly, Parm
    CoreUObject::UObject* Asset;                 // 0x0020(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash

};

// 0x004
// Function /Game/ASA/UI/OptionSelector_Widget.OptionSelector_Widget_C.ExecuteUbergraph_OptionSelector_Widget
struct UOptionSelector_Widget_C_ExecuteUbergraph_OptionSelector_Widget_Params final
{
public:
    int32_t EntryPoint; // 0x0000(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
