// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::PhysicsCore
{
// ScriptStruct /Script/PhysicsCore.BodyInstanceCore
// 0x00C
struct FBodyInstanceCore
{
public:
    uint8_t FBodyInstanceCore_PrePadding[0x8];   // 0x0000(0x0008) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    bool    bSimulatePhysics: 0x1;               // 0x0008(0x0001) BIT_FIELD(0x0) Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool    bOverrideMass: 0x1;                  // 0x0008(0x0001) BIT_FIELD(0x1) Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool    bEnableGravity: 0x1;                 // 0x0008(0x0001) BIT_FIELD(0x2) Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool    bUpdateKinematicFromSimulation: 0x1; // 0x0008(0x0001) BIT_FIELD(0x3) Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool    bAutoWeld: 0x1;                      // 0x0008(0x0001) BIT_FIELD(0x4) Edit, BlueprintVisible, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool    bStartAwake: 0x1;                    // 0x0008(0x0001) BIT_FIELD(0x5) Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool    bGenerateWakeEvents: 0x1;            // 0x0008(0x0001) BIT_FIELD(0x6) Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic
    bool    bUpdateMassWhenScaleChanges: 0x1;    // 0x0008(0x0001) BIT_FIELD(0x7) Edit, BlueprintVisible, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic
    uint8_t FBodyInstanceCore_Padding[0x3];      // 0x0009(0x0003) MISSED OFFSET (FIX STRUCT SIZE)

};

// ScriptStruct /Script/PhysicsCore.PhysicalMaterialDamageModifier
// 0x004
struct FPhysicalMaterialDamageModifier
{
public:
    float DamageThresholdMultiplier; // 0x0000(0x0004) Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic

};

// ScriptStruct /Script/PhysicsCore.PhysicalMaterialStrength
// 0x00C
struct FPhysicalMaterialStrength
{
public:
    float TensileStrength;     // 0x0000(0x0004) Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    float CompressionStrength; // 0x0004(0x0004) Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    float ShearStrength;       // 0x0008(0x0004) Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
