// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_STRUCTS.h"
#include "PrimalItemWeaponGenericNoStats_CLASSES.h"

namespace CG::BasicTypes { class FName; }
namespace CG::CoreUObject { class UClass; }
namespace CG::ShooterGame { class AShooterPlayerController; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::PrimalItem_WeaponSpyglass
{
// BlueprintGeneratedClass /Game/PrimalEarth/Test/PrimalItem_WeaponSpyglass.PrimalItem_WeaponSpyglass_C
// 0x017(0xB6A - 0xB53)
class UPrimalItem_WeaponSpyglass_C : public PrimalItemWeaponGenericNoStats::UPrimalItemWeaponGenericNoStats_C
{
public:
    uint8_t                                UPrimalItem_WeaponSpyglass_C_PrePadding[0x5]; // 0x0B53(0x0005) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    Engine::FPointerToUberGraphFrame       UberGraphFrame;                               // 0x0B58(0x0008) ZeroConstructor, Transient, DuplicateTransient
    ShooterGame::AShooterPlayerController* For_PC;                                       // 0x0B60(0x0008) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash
    bool                                   UsedWeapon;                                   // 0x0B68(0x0001) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    bool                                   ShouldTrack;                                  // 0x0B69(0x0001) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash

public:
    bool CanUseItemPing();
    bool BPPreventWeaponEquip();
    void TimerDoubleTap();
    void TimerUsePingWheel();
    void LocalUseStartHoldBP(ShooterGame::AShooterPlayerController* ForPC);
    void LocalUseItemReleaseBP(ShooterGame::AShooterPlayerController* ForPC);
    void LocalUseAfterHoldBP(ShooterGame::AShooterPlayerController* ForPC);
    void BPServerHandleItemNetExecCommand(ShooterGame::AShooterPlayerController* ForPC, const BasicTypes::FName& CommandName, const Engine::FBPNetExecParams& ExecParams);
    void ExecuteUbergraph_PrimalItem_WeaponSpyglass(int32_t EntryPoint);
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
