// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "PrimalItemResourceGeneric_CLASSES.h"

namespace CG::CoreUObject { class UClass; }
namespace CG::ShooterGame { class UPrimalItem; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::PrimalItemResource_ElementShard
{
// BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ElementShard.PrimalItemResource_ElementShard_C
// 0x000(0xB53 - 0xB53)
class UPrimalItemResource_ElementShard_C : public PrimalItemResourceGeneric::UPrimalItemResourceGeneric_C
{
public:
    void RefillElementShard(ShooterGame::UPrimalItem* DestinationItem);
    void CheckForElementShardData(ShooterGame::UPrimalItem* DestinationItem, bool SupportsDragOnto);
    bool BPSupportUseOntoItem(ShooterGame::UPrimalItem* DestinationItem);
    void BPUsedOntoItem(ShooterGame::UPrimalItem* DestinationItem, int32_t AdditionalData);
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
