// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "PrimalItemConsumable_Kibble_Base_Medium_CLASSES.h"

namespace CG::CoreUObject { class UClass; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::PrimalItemConsumable_Kibble_AnkyloEgg
{
// BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_AnkyloEgg.PrimalItemConsumable_Kibble_AnkyloEgg_C
// 0x000(0xB53 - 0xB53)
class UPrimalItemConsumable_Kibble_AnkyloEgg_C : public PrimalItemConsumable_Kibble_Base_Medium::UPrimalItemConsumable_Kibble_Base_Medium_C
{
public:
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
