// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"
#include "CoreUObject_STRUCTS.h"

namespace CG::Engine { class AActor; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::ScorchedEarthDayCycle_Interface
{
// 0x028
// Function /Game/ScorchedEarth/CoreBlueprints/Core/ScorchedEarthDayCycle_Interface.ScorchedEarthDayCycle_Interface_C.GetIsInsideSandstormSweep
struct IScorchedEarthDayCycle_Interface_C_GetIsInsideSandstormSweep_Params final
{
public:
    CoreUObject::FVector Location;              // 0x0000(0x0018) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    bool                 bIsInside;             // 0x0018(0x0001) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t              UnknownData_0000[0x7]; // 0x0019(0x0007)
    double               Lerp;                  // 0x0020(0x0008) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x001
// Function /Game/ScorchedEarth/CoreBlueprints/Core/ScorchedEarthDayCycle_Interface.ScorchedEarthDayCycle_Interface_C.GetIsElectricalStorm
struct IScorchedEarthDayCycle_Interface_C_GetIsElectricalStorm_Params final
{
public:
    bool Return; // 0x0000(0x0001) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x020
// Function /Game/ScorchedEarth/CoreBlueprints/Core/ScorchedEarthDayCycle_Interface.ScorchedEarthDayCycle_Interface_C.GetElectricalStormValues
struct IScorchedEarthDayCycle_Interface_C_GetElectricalStormValues_Params final
{
public:
    BasicTypes::TArray<Engine::AActor*> LocationRegions;       // 0x0000(0x0010) Parm, OutParm
    int32_t                             CurrentRegion;         // 0x0010(0x0004) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t                             UnknownData_0001[0x4]; // 0x0014(0x0004)
    double                              Radius;                // 0x0018(0x0008) Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
