// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "ShooterGame_CLASSES.h"

namespace CG::CoreUObject { class UClass; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::ServerChatMessage
{
// WidgetBlueprintGeneratedClass /Game/PrimalEarth/UI/ServerChatMessage.ServerChatMessage_C
// 0x000(0x890 - 0x890)
class UServerChatMessage_C : public ShooterGame::UUI_ServerBroadcastMessage
{
public:
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
