// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "ServerSidePoint_CLASSES.h"

namespace CG::CoreUObject { class UClass; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::ServerSidePoint_Huge
{
// BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/ServerSidePoint_Huge.ServerSidePoint_Huge_C
// 0x000(0x480 - 0x480)
class AServerSidePoint_Huge_C : public ServerSidePoint::AServerSidePoint_C
{
public:
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
