// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"
#include "Engine_STRUCTS.h"

namespace CG::CoreUObject { class UClass; }
namespace CG::Engine { class AActor; }
namespace CG::Engine { class APlayerController; }
namespace CG::Engine { class USplineComponent; }
namespace CG::ShooterGame { class APrimalDinoCharacter; }
namespace CG::ShooterGame { class UPrimalItem; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Structure_TrainCart_Base
{
// 0x001
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.UpdateTameCount
struct AStructure_TrainCart_Base_C_UpdateTameCount_Params final
{
public:
    bool bForceDecrement; // 0x0000(0x0001) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x008
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.BPGetAttachedToCharacter
struct AStructure_TrainCart_Base_C_BPGetAttachedToCharacter_Params final
{
public:
    ShooterGame::APrimalDinoCharacter* ReturnValue; // 0x0000(0x0008) Parm, OutParm, ReturnParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash

};

// 0x009
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.BPAllowPickupGiveItem
struct AStructure_TrainCart_Base_C_BPAllowPickupGiveItem_Params final
{
public:
    Engine::APlayerController* ForPC;       // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    bool                       ReturnValue; // 0x0008(0x0001) Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.ClearNetworkParent
struct AStructure_TrainCart_Base_C_ClearNetworkParent_Params final
{

};

// 0x008
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.SetTrain
struct AStructure_TrainCart_Base_C_SetTrain_Params final
{
public:
    Engine::AActor* MyTrain; // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash

};

// 0x00C
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.BPClientDoMultiUse
struct AStructure_TrainCart_Base_C_BPClientDoMultiUse_Params final
{
public:
    Engine::APlayerController* ForPC;          // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    int32_t                    ClientUseIndex; // 0x0008(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x034
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.UpdateMovementValues
struct AStructure_TrainCart_Base_C_UpdateMovementValues_Params final
{
public:
    bool                      bIsMoving;                   // 0x0000(0x0001) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t                   UnknownData_0000[0x7];       // 0x0001(0x0007)
    double                    LastMovementSpeed;           // 0x0008(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    double                    LastDistance;                // 0x0010(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    Engine::AActor*           LastTrack;                   // 0x0018(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    int32_t                   LastTrackIndex;              // 0x0020(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t                   UnknownData_0001[0x4];       // 0x0024(0x0004)
    Engine::USplineComponent* LastTrackSpline;             // 0x0028(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash
    int32_t                   LastTrainSelectedTrackIndex; // 0x0030(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.AttachLinkedStructures
struct AStructure_TrainCart_Base_C_AttachLinkedStructures_Params final
{

};

// 0x00D
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.BPTryMultiUse
struct AStructure_TrainCart_Base_C_BPTryMultiUse_Params final
{
public:
    Engine::APlayerController* ForPC;       // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    int32_t                    UseIndex;    // 0x0008(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    bool                       ReturnValue; // 0x000C(0x0001) Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x028
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.BPGetMultiUseEntries
struct AStructure_TrainCart_Base_C_BPGetMultiUseEntries_Params final
{
public:
    Engine::APlayerController*                 ForPC;           // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    BasicTypes::TArray<Engine::FMultiUseEntry> MultiUseEntries; // 0x0008(0x0010) BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm, ContainsInstancedReference
    BasicTypes::TArray<Engine::FMultiUseEntry> ReturnValue;     // 0x0018(0x0010) Parm, OutParm, ReturnParm, ContainsInstancedReference

};

// 0x000
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.UserConstructionScript
struct AStructure_TrainCart_Base_C_UserConstructionScript_Params final
{

};

// 0x019
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.BPOnStructurePickup
struct AStructure_TrainCart_Base_C_BPOnStructurePickup_Params final
{
public:
    Engine::APlayerController* PlayerController;  // 0x0000(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    CoreUObject::UClass*       ItemType;          // 0x0008(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash
    ShooterGame::UPrimalItem*  NewlyPickedUpItem; // 0x0010(0x0008) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
    bool                       bIsQuickPickup;    // 0x0018(0x0001) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.ReceiveDestroyed
struct AStructure_TrainCart_Base_C_ReceiveDestroyed_Params final
{

};

// 0x000
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.ReceiveBeginPlay
struct AStructure_TrainCart_Base_C_ReceiveBeginPlay_Params final
{

};

// 0x000
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.BPChangedActorTeam
struct AStructure_TrainCart_Base_C_BPChangedActorTeam_Params final
{

};

// 0x004
// Function /Game/Packs/Frontier/Structures/TrainCarts/Structure_TrainCart_Base.Structure_TrainCart_Base_C.ExecuteUbergraph_Structure_TrainCart_Base
struct AStructure_TrainCart_Base_C_ExecuteUbergraph_Structure_TrainCart_Base_Params final
{
public:
    int32_t EntryPoint; // 0x0000(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
