// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_STRUCTS.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Therizinosaurus_GroundConform_AnimBlueprint
{
// 0x020
// Function /Game/PrimalEarth/Dinos/Therizinosaurus/Rig/Therizinosaurus_GroundConform_AnimBlueprint.Therizinosaurus_GroundConform_AnimBlueprint_C.AnimGraph
struct UTherizinosaurus_GroundConform_AnimBlueprint_C_AnimGraph_Params final
{
public:
    Engine::FPoseLink InPose;    // 0x0000(0x0010) BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor
    Engine::FPoseLink AnimGraph; // 0x0010(0x0010) Parm, OutParm, NoDestructor

};

// 0x000
// Function /Game/PrimalEarth/Dinos/Therizinosaurus/Rig/Therizinosaurus_GroundConform_AnimBlueprint.Therizinosaurus_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Therizinosaurus_GroundConform_AnimBlueprint_AnimGraphNode_ApplyAdditive_D5DA3F1D4074CFBD8CC3D187E2F62168
struct UTherizinosaurus_GroundConform_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Therizinosaurus_GroundConform_AnimBlueprint_AnimGraphNode_ApplyAdditive_D5DA3F1D4074CFBD8CC3D187E2F62168_Params final
{

};

// 0x000
// Function /Game/PrimalEarth/Dinos/Therizinosaurus/Rig/Therizinosaurus_GroundConform_AnimBlueprint.Therizinosaurus_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Therizinosaurus_GroundConform_AnimBlueprint_AnimGraphNode_ModifyBone_8F9E708B4D9B25BD1A5EA39C88F41A67
struct UTherizinosaurus_GroundConform_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Therizinosaurus_GroundConform_AnimBlueprint_AnimGraphNode_ModifyBone_8F9E708B4D9B25BD1A5EA39C88F41A67_Params final
{

};

// 0x000
// Function /Game/PrimalEarth/Dinos/Therizinosaurus/Rig/Therizinosaurus_GroundConform_AnimBlueprint.Therizinosaurus_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Therizinosaurus_GroundConform_AnimBlueprint_AnimGraphNode_TwoWayBlend_C292AD75424C0AA9A84BB7A3DB3F2FAF
struct UTherizinosaurus_GroundConform_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Therizinosaurus_GroundConform_AnimBlueprint_AnimGraphNode_TwoWayBlend_C292AD75424C0AA9A84BB7A3DB3F2FAF_Params final
{

};

// 0x004
// Function /Game/PrimalEarth/Dinos/Therizinosaurus/Rig/Therizinosaurus_GroundConform_AnimBlueprint.Therizinosaurus_GroundConform_AnimBlueprint_C.BlueprintUpdateAnimation
struct UTherizinosaurus_GroundConform_AnimBlueprint_C_BlueprintUpdateAnimation_Params final
{
public:
    float DeltaTimeX; // 0x0000(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};

// 0x000
// Function /Game/PrimalEarth/Dinos/Therizinosaurus/Rig/Therizinosaurus_GroundConform_AnimBlueprint.Therizinosaurus_GroundConform_AnimBlueprint_C.BlueprintInitializeAnimation
struct UTherizinosaurus_GroundConform_AnimBlueprint_C_BlueprintInitializeAnimation_Params final
{

};

// 0x004
// Function /Game/PrimalEarth/Dinos/Therizinosaurus/Rig/Therizinosaurus_GroundConform_AnimBlueprint.Therizinosaurus_GroundConform_AnimBlueprint_C.ExecuteUbergraph_Therizinosaurus_GroundConform_AnimBlueprint
struct UTherizinosaurus_GroundConform_AnimBlueprint_C_ExecuteUbergraph_Therizinosaurus_GroundConform_AnimBlueprint_Params final
{
public:
    int32_t EntryPoint; // 0x0000(0x0004) BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash

};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
