// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"
#include "ShooterGame_STRUCTS.h"
#include "TraitValueModifications_ENUMS.h"
#include "Trait_Base_CLASSES.h"

namespace CG::CoreUObject { class UClass; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Trait_SlowMetabolism
{
// BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/GeneTraits/TraitBPs/SlowMetabolism/Trait_SlowMetabolism.Trait_SlowMetabolism_C
// 0x044(0x1A0 - 0x15C)
class UTrait_SlowMetabolism_C : public Trait_Base::UTrait_Base_C
{
public:
    uint8_t                   UTrait_SlowMetabolism_C_PrePadding[0x4]; // 0x015C(0x0004) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    BasicTypes::TArray<float> Multipliers;                             // 0x0160(0x0010) Edit, BlueprintVisible, DisableEditOnInstance
    BasicTypes::FString       GainsString;                             // 0x0170(0x0010) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash
    BasicTypes::FText         ReducedFoodString;                       // 0x0180(0x0010) Edit, BlueprintVisible, DisableEditOnInstance
    BasicTypes::FString       NewlineString;                           // 0x0190(0x0010) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash

public:
    void GetFullDescription__with_tier_and_drag_weight_alpha_already_obtained_(ShooterGame::FFunctionParams_NoArrays& In_Data, int32_t Tier, float Drag_Weight_Alpha_from_1_0_to_Value, BasicTypes::FString& Full_Description);
    void IsTraitAllowedToBeOnThisCreature(ShooterGame::FFunctionParams_NoArrays& InData, bool IsAllowed);
    void GetSpecificationForAdjustingValue(TraitValueModifications::ETraitValueModifications Effect, uint8_t Tier, BasicTypes::FString& Reason);
    bool BPGetCustomBlueprintData(const BasicTypes::FName& DataName, ShooterGame::FFunctionParams_NoArrays InData, ShooterGame::FFunctionParams_NoArrays& OutData);
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
