// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "Trait_Inherit_HP_Base_CLASSES.h"

namespace CG::CoreUObject { class UClass; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Trait_Inherit_HP_Frail
{
// BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/GeneTraits/TraitBPs/Inherit/Health/Frail/Trait_Inherit_HP_Frail.Trait_Inherit_HP_Frail_C
// 0x000(0x290 - 0x290)
class UTrait_Inherit_HP_Frail_C : public Trait_Inherit_HP_Base::UTrait_Inherit_HP_Base_C
{
public:
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
