// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#pragma once

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_CLASSES.h"
#include "Engine_STRUCTS.h"
#include "ShooterGame_CLASSES.h"
#include "ShooterGame_STRUCTS.h"

namespace CG::CoreUObject { class UClass; }
namespace CG::UMG { class UImage; }
namespace CG::UMG { class UOverlay; }
namespace CG::UMG { class UProgressBar; }
namespace CG::UMG { class UTextBlock; }
namespace CG::UMG { class UWidgetAnimation; }

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::W_MilestoneNotificationNewPointBP
{
// WidgetBlueprintGeneratedClass /Game/ASA/UI/SkillTree/Milestones/W_MilestoneNotificationNewPointBP.W_MilestoneNotificationNewPointBP_C
// 0x0E0(0x458 - 0x378)
class UW_MilestoneNotificationNewPointBP_C : public ShooterGame::UW_MilestoneNotification
{
public:
    Engine::FPointerToUberGraphFrame UberGraphFrame;             // 0x0378(0x0008) ZeroConstructor, Transient, DuplicateTransient
    UMG::UWidgetAnimation*           Close;                      // 0x0380(0x0008) BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash
    UMG::UWidgetAnimation*           Open;                       // 0x0388(0x0008) BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash
    UMG::UTextBlock*                 Description;                // 0x0390(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    UMG::UTextBlock*                 Description_2;              // 0x0398(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    UMG::UTextBlock*                 Description_3;              // 0x03A0(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    UMG::UImage*                     Image_1;                    // 0x03A8(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    UMG::UImage*                     Image_2;                    // 0x03B0(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    UMG::UImage*                     Image_42;                   // 0x03B8(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    UMG::UOverlay*                   Overlay_2;                  // 0x03C0(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    UMG::UProgressBar*               RedBar;                     // 0x03C8(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    UMG::UProgressBar*               WhiteBar;                   // 0x03D0(0x0008) BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash
    ShooterGame::FPrimalMilestone    Data_;                      // 0x03D8(0x0060) Edit, BlueprintVisible, DisableEditOnInstance
    BasicTypes::FName                ID;                         // 0x0438(0x0008) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    double                           TargetProgress;             // 0x0440(0x0008) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    bool                             bWasCompleted;              // 0x0448(0x0001) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    uint8_t                          bWasCompleted_Padding[0x7]; // 0x0449(0x0007) MISSED OFFSET (FILLING OFFSET GAP FROM PREVIOUS PROPERTY)
    double                           Previous_Progress;          // 0x0450(0x0008) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash

public:
    void Construct();
    void SelfDestroy();
    void ExecuteUbergraph_W_MilestoneNotificationNewPointBP(int32_t EntryPoint);
    static CoreUObject::UClass* StaticClass();
};
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
