// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/AnimationBudgetAllocator_CLASSES.h"
#include "Headers/AnimationBudgetAllocator_PARAMETERS.h"
#include "Headers/AnimationBudgetAllocator_STRUCTS.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/Engine_CLASSES.h"

namespace CG::AnimationBudgetAllocator
{

// Name:   Function /Script/AnimationBudgetAllocator.AnimationBudgetBlueprintLibrary.SetAnimationBudgetParameters
// Flags:  Final, Native, Static, Private, HasOutParms, BlueprintCallable
// RVA:    0x8BF5E30
// Params:
//   WorldContextObject           0x000(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   InParameters                 0x008(0x058), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
void UAnimationBudgetBlueprintLibrary::STATIC_SetAnimationBudgetParameters(CoreUObject::UObject* WorldContextObject, const FAnimationBudgetAllocatorParameters& InParameters)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/AnimationBudgetAllocator.AnimationBudgetBlueprintLibrary.SetAnimationBudgetParameters");

    UAnimationBudgetBlueprintLibrary_SetAnimationBudgetParameters_Params params {};
    params.WorldContextObject = WorldContextObject;
    params.InParameters = InParameters;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Script/AnimationBudgetAllocator.AnimationBudgetBlueprintLibrary.EnableAnimationBudget
// Flags:  Final, Native, Static, Private, BlueprintCallable
// RVA:    0x8BF5B40
// Params:
//   WorldContextObject           0x000(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   bEnabled                     0x008(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
void UAnimationBudgetBlueprintLibrary::STATIC_EnableAnimationBudget(CoreUObject::UObject* WorldContextObject, bool bEnabled)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/AnimationBudgetAllocator.AnimationBudgetBlueprintLibrary.EnableAnimationBudget");

    UAnimationBudgetBlueprintLibrary_EnableAnimationBudget_Params params {};
    params.WorldContextObject = WorldContextObject;
    params.bEnabled = bEnabled;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction Class /Script/AnimationBudgetAllocator.AnimationBudgetBlueprintLibrary.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UAnimationBudgetBlueprintLibrary::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/AnimationBudgetAllocator.AnimationBudgetBlueprintLibrary");
    return ptr;
}

// Name:   Function /Script/AnimationBudgetAllocator.SkeletalMeshComponentBudgeted.SetAutoRegisterWithBudgetAllocator
// Flags:  Final, Native, Public, BlueprintCallable
// RVA:    0x8BF6340
// Params:
//   bInAutoRegisterWithBudgetAllocator 0x000(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
void USkeletalMeshComponentBudgeted::SetAutoRegisterWithBudgetAllocator(bool bInAutoRegisterWithBudgetAllocator)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/AnimationBudgetAllocator.SkeletalMeshComponentBudgeted.SetAutoRegisterWithBudgetAllocator");

    USkeletalMeshComponentBudgeted_SetAutoRegisterWithBudgetAllocator_Params params {};
    params.bInAutoRegisterWithBudgetAllocator = bInAutoRegisterWithBudgetAllocator;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction Class /Script/AnimationBudgetAllocator.SkeletalMeshComponentBudgeted.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* USkeletalMeshComponentBudgeted::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/AnimationBudgetAllocator.SkeletalMeshComponentBudgeted");
    return ptr;
}
}

