// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/AnimGraphRuntime_ENUMS.h"
#include "Headers/AnimGraphRuntime_STRUCTS.h"
#include "Headers/AnimationWarpingRuntime_CLASSES.h"
#include "Headers/AnimationWarpingRuntime_ENUMS.h"
#include "Headers/AnimationWarpingRuntime_PARAMETERS.h"
#include "Headers/AnimationWarpingRuntime_STRUCTS.h"
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/CoreUObject_ENUMS.h"
#include "Headers/CoreUObject_STRUCTS.h"
#include "Headers/Engine_CLASSES.h"
#include "Headers/Engine_ENUMS.h"
#include "Headers/Engine_STRUCTS.h"

namespace CG::AnimationWarpingRuntime
{
















// Name:   Function /Script/AnimationWarpingRuntime.AnimationWarpingLibrary.GetOffsetRootTransform
// Flags:  Final, Native, Static, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintPure
// RVA:    0x761E000
// Params:
//   Node                         0x000(0x010), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x010(0x060), Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
CoreUObject::FTransform UAnimationWarpingLibrary::STATIC_GetOffsetRootTransform(const Engine::FAnimNodeReference& Node)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/AnimationWarpingRuntime.AnimationWarpingLibrary.GetOffsetRootTransform");

    UAnimationWarpingLibrary_GetOffsetRootTransform_Params params {};
    params.Node = Node;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/AnimationWarpingRuntime.AnimationWarpingLibrary.GetCurveValueFromAnimation
// Flags:  Final, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x761DC30
// Params:
//   Animation                    0x000(0x008), Parm, ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   CurveName                    0x008(0x008), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   Time                         0x010(0x004), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   OutValue                     0x014(0x004), Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x018(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UAnimationWarpingLibrary::STATIC_GetCurveValueFromAnimation(Engine::UAnimSequenceBase* Animation, const BasicTypes::FName& CurveName, float Time, float& OutValue)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/AnimationWarpingRuntime.AnimationWarpingLibrary.GetCurveValueFromAnimation");

    UAnimationWarpingLibrary_GetCurveValueFromAnimation_Params params {};
    params.Animation = Animation;
    params.CurveName = CurveName;
    params.Time = Time;
    params.OutValue = OutValue;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    OutValue = params.OutValue;

    return params.ReturnValue;
}

// Name:   PredefinedFunction Class /Script/AnimationWarpingRuntime.AnimationWarpingLibrary.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UAnimationWarpingLibrary::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/AnimationWarpingRuntime.AnimationWarpingLibrary");
    return ptr;
}
}

