// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/BP_CFCoreUIModel_CLASSES.h"
#include "Headers/BP_CFCoreUIModel_PARAMETERS.h"
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/cfcore_STRUCTS.h"
#include "Headers/cfcore_ui_CLASSES.h"
#include "Headers/cfcore_ui_ENUMS.h"
#include "Headers/cfcore_ui_STRUCTS.h"

namespace CG::BP_CFCoreUIModel
{
// Name:   Function /cfcore_ui/Tools/Blueprints/BP_CFCoreUIModel.BP_CFCoreUIModel_C.OnEventReceived
// Flags:  Event, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   evt                          0x000(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   InModsList                   0x008(0x010), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
//   OutModsList                  0x018(0x010), Parm, OutParm, ContainsInstancedReference
//   ReturnValue                  0x028(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool UBP_CFCoreUIModel_C::OnEventReceived(const cfcore_ui::EGameModsEvent& evt, const BasicTypes::TArray<cfcore::FCFCoreMod>& InModsList, BasicTypes::TArray<cfcore_ui::FInstallProgressMod>& OutModsList)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /cfcore_ui/Tools/Blueprints/BP_CFCoreUIModel.BP_CFCoreUIModel_C.OnEventReceived");

    UBP_CFCoreUIModel_C_OnEventReceived_Params params {};
    params.evt = evt;
    params.InModsList = InModsList;
    params.OutModsList = OutModsList;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    OutModsList = params.OutModsList;

    return params.ReturnValue;
}

// Name:   Function /cfcore_ui/Tools/Blueprints/BP_CFCoreUIModel.BP_CFCoreUIModel_C.OnEventReceived_LibraryProgress
// Flags:  Event, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   evt                          0x000(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   progress                     0x008(0x040), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
//   OutModsList                  0x048(0x010), Parm, OutParm, ContainsInstancedReference
//   ReturnValue                  0x058(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool UBP_CFCoreUIModel_C::OnEventReceived_LibraryProgress(const cfcore_ui::EGameModsEvent& evt, const cfcore::FLibraryProgress& progress, BasicTypes::TArray<cfcore_ui::FInstallProgressMod>& OutModsList)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /cfcore_ui/Tools/Blueprints/BP_CFCoreUIModel.BP_CFCoreUIModel_C.OnEventReceived_LibraryProgress");

    UBP_CFCoreUIModel_C_OnEventReceived_LibraryProgress_Params params {};
    params.evt = evt;
    params.progress = progress;
    params.OutModsList = OutModsList;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    OutModsList = params.OutModsList;

    return params.ReturnValue;
}

// Name:   PredefinedFunction BlueprintGeneratedClass /cfcore_ui/Tools/Blueprints/BP_CFCoreUIModel.BP_CFCoreUIModel_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UBP_CFCoreUIModel_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /cfcore_ui/Tools/Blueprints/BP_CFCoreUIModel.BP_CFCoreUIModel_C");
    return ptr;
}
}

