// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/BP_WaterPhysics_Base_CLASSES.h"
#include "Headers/BP_WaterPhysics_Base_PARAMETERS.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/Engine_CLASSES.h"

namespace CG::BP_WaterPhysics_Base
{
// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/Utilities/WaterTool/Volumes/BP_WaterPhysics_Base.BP_WaterPhysics_Base_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* ABP_WaterPhysics_Base_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/Utilities/WaterTool/Volumes/BP_WaterPhysics_Base.BP_WaterPhysics_Base_C");
    return ptr;
}
}

