// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CheatMenuFolderButton_CLASSES.h"
#include "Headers/CheatMenuFolderButton_PARAMETERS.h"
#include "Headers/CheatMenu_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/Engine_CLASSES.h"
#include "Headers/Engine_STRUCTS.h"
#include "Headers/ShooterGame_CLASSES.h"
#include "Headers/UMG_CLASSES.h"

namespace CG::CheatMenuFolderButton
{
// Name:   Function /Game/PrimalEarth/UI/CheatMenu/CheatMenuFolderButton.CheatMenuFolderButton_C.SetFolder
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   FolderName                   0x000(0x010), BlueprintVisible, BlueprintReadOnly, Parm
//   ScreenNumber                 0x010(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   Image                        0x018(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
void UCheatMenuFolderButton_C::SetFolder(const BasicTypes::FText& FolderName, int32_t ScreenNumber, Engine::UTexture2D* Image)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/UI/CheatMenu/CheatMenuFolderButton.CheatMenuFolderButton_C.SetFolder");

    UCheatMenuFolderButton_C_SetFolder_Params params {};
    params.FolderName = FolderName;
    params.ScreenNumber = ScreenNumber;
    params.Image = Image;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/UI/CheatMenu/CheatMenuFolderButton.CheatMenuFolderButton_C.BndEvt__SpawnButton_K2Node_ComponentBoundEvent_160_OnButtonClickedEvent__DelegateSignature
// Flags:  BlueprintEvent
// RVA:    0x17D3880
// Params:
void UCheatMenuFolderButton_C::BndEvt__SpawnButton_K2Node_ComponentBoundEvent_160_OnButtonClickedEvent__DelegateSignature()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/UI/CheatMenu/CheatMenuFolderButton.CheatMenuFolderButton_C.BndEvt__SpawnButton_K2Node_ComponentBoundEvent_160_OnButtonClickedEvent__DelegateSignature");

    UCheatMenuFolderButton_C_BndEvt__SpawnButton_K2Node_ComponentBoundEvent_160_OnButtonClickedEvent__DelegateSignature_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/UI/CheatMenu/CheatMenuFolderButton.CheatMenuFolderButton_C.ExecuteUbergraph_CheatMenuFolderButton
// Flags:  Final, UberGraphFunction
// RVA:    0x17D3880
// Params:
//   EntryPoint                   0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void UCheatMenuFolderButton_C::ExecuteUbergraph_CheatMenuFolderButton(int32_t EntryPoint)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/UI/CheatMenu/CheatMenuFolderButton.CheatMenuFolderButton_C.ExecuteUbergraph_CheatMenuFolderButton");

    UCheatMenuFolderButton_C_ExecuteUbergraph_CheatMenuFolderButton_Params params {};
    params.EntryPoint = EntryPoint;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction WidgetBlueprintGeneratedClass /Game/PrimalEarth/UI/CheatMenu/CheatMenuFolderButton.CheatMenuFolderButton_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UCheatMenuFolderButton_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("WidgetBlueprintGeneratedClass /Game/PrimalEarth/UI/CheatMenu/CheatMenuFolderButton.CheatMenuFolderButton_C");
    return ptr;
}
}

