// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/DinoCharacterStatusComponent_BP_CLASSES.h"
#include "Headers/DinoCharacterStatusComponent_BP_TorpidityControl_CLASSES.h"
#include "Headers/DinoCharacterStatusComponent_BP_TorpidityControl_PARAMETERS.h"
#include "Headers/ShooterGame_ENUMS.h"

namespace CG::DinoCharacterStatusComponent_BP_TorpidityControl
{
// Name:   Function /Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_TorpidityControl.DinoCharacterStatusComponent_BP_TorpidityControl_C.BPAdjustStatusValueModification
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   ValueType                    0x000(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   Amount                       0x004(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   DamageTypeClass              0x008(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash
//   bManualModification          0x010(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   ReturnValue                  0x014(0x004), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
float UDinoCharacterStatusComponent_BP_TorpidityControl_C::BPAdjustStatusValueModification(ShooterGame::EPrimalCharacterStatusValue ValueType, float Amount, CoreUObject::UClass* DamageTypeClass, bool bManualModification)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_TorpidityControl.DinoCharacterStatusComponent_BP_TorpidityControl_C.BPAdjustStatusValueModification");

    UDinoCharacterStatusComponent_BP_TorpidityControl_C_BPAdjustStatusValueModification_Params params {};
    params.ValueType = ValueType;
    params.Amount = Amount;
    params.DamageTypeClass = DamageTypeClass;
    params.bManualModification = bManualModification;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_TorpidityControl.DinoCharacterStatusComponent_BP_TorpidityControl_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UDinoCharacterStatusComponent_BP_TorpidityControl_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_TorpidityControl.DinoCharacterStatusComponent_BP_TorpidityControl_C");
    return ptr;
}
}

