// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/DinoSettings_Carnivore_CLASSES.h"
#include "Headers/DinoSettings_Carnivore_Huge_CLASSES.h"
#include "Headers/DinoSettings_Carnivore_Huge_PARAMETERS.h"

namespace CG::DinoSettings_Carnivore_Huge
{
// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/Dinos/BaseBPs/DinoSettings_Carnivore_Huge.DinoSettings_Carnivore_Huge_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UDinoSettings_Carnivore_Huge_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/Dinos/BaseBPs/DinoSettings_Carnivore_Huge.DinoSettings_Carnivore_Huge_C");
    return ptr;
}
}

