// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/DmgType_GeneScanner_Base_CLASSES.h"
#include "Headers/DmgType_GeneScanner_Base_PARAMETERS.h"
#include "Headers/DmgType_Melee_Torpidity_Low_MetalWeapon_CLASSES.h"

namespace CG::DmgType_GeneScanner_Base
{
// Name:   PredefinedFunction BlueprintGeneratedClass /Game/Packs/Steampunk/Weapons/GeneScanner/BaseClasses/DmgType_GeneScanner_Base.DmgType_GeneScanner_Base_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UDmgType_GeneScanner_Base_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/Packs/Steampunk/Weapons/GeneScanner/BaseClasses/DmgType_GeneScanner_Base.DmgType_GeneScanner_Base_C");
    return ptr;
}
}

