// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/DmgType_Instant_CLASSES.h"
#include "Headers/DmgType_Instant_PiercingGeneral_CLASSES.h"
#include "Headers/DmgType_Instant_PiercingGeneral_PARAMETERS.h"

namespace CG::DmgType_Instant_PiercingGeneral
{
// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/DamageTypes/DmgType_Instant_PiercingGeneral.DmgType_Instant_PiercingGeneral_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UDmgType_Instant_PiercingGeneral_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/DamageTypes/DmgType_Instant_PiercingGeneral.DmgType_Instant_PiercingGeneral_C");
    return ptr;
}
}

