// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/CoreUObject_STRUCTS.h"
#include "Headers/DeveloperSettings_CLASSES.h"
#include "Headers/Engine_CLASSES.h"
#include "Headers/Engine_STRUCTS.h"
#include "Headers/GameplayTags_CLASSES.h"
#include "Headers/GameplayTags_ENUMS.h"
#include "Headers/GameplayTags_PARAMETERS.h"
#include "Headers/GameplayTags_STRUCTS.h"
#include "Headers/IrisStub_STRUCTS.h"

namespace CG::GameplayTags
{














// Name:   Function /Script/GameplayTags.GameplayTagAssetInterface.HasMatchingGameplayTag
// Flags:  RequiredAPI, Native, Public, BlueprintCallable, BlueprintPure, Const
// RVA:    0x3E9AC20
// Params:
//   TagToCheck                   0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool IGameplayTagAssetInterface::HasMatchingGameplayTag(FGameplayTag TagToCheck) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.GameplayTagAssetInterface.HasMatchingGameplayTag");

    IGameplayTagAssetInterface_HasMatchingGameplayTag_Params params {};
    params.TagToCheck = TagToCheck;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.GameplayTagAssetInterface.HasAnyMatchingGameplayTags
// Flags:  RequiredAPI, Native, Public, HasOutParms, BlueprintCallable, BlueprintPure, Const
// RVA:    0x3E9AAB0
// Params:
//   TagContainer                 0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x020(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool IGameplayTagAssetInterface::HasAnyMatchingGameplayTags(const FGameplayTagContainer& TagContainer) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.GameplayTagAssetInterface.HasAnyMatchingGameplayTags");

    IGameplayTagAssetInterface_HasAnyMatchingGameplayTags_Params params {};
    params.TagContainer = TagContainer;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.GameplayTagAssetInterface.HasAllMatchingGameplayTags
// Flags:  RequiredAPI, Native, Public, HasOutParms, BlueprintCallable, BlueprintPure, Const
// RVA:    0x3E9A940
// Params:
//   TagContainer                 0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x020(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool IGameplayTagAssetInterface::HasAllMatchingGameplayTags(const FGameplayTagContainer& TagContainer) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.GameplayTagAssetInterface.HasAllMatchingGameplayTags");

    IGameplayTagAssetInterface_HasAllMatchingGameplayTags_Params params {};
    params.TagContainer = TagContainer;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.GameplayTagAssetInterface.BP_GetOwnedGameplayTags
// Flags:  RequiredAPI, Native, Protected, BlueprintCallable, BlueprintPure, Const
// RVA:    0x3E9A8A0
// Params:
//   ReturnValue                  0x000(0x020), Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic
FGameplayTagContainer IGameplayTagAssetInterface::BP_GetOwnedGameplayTags() const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.GameplayTagAssetInterface.BP_GetOwnedGameplayTags");

    IGameplayTagAssetInterface_BP_GetOwnedGameplayTags_Params params {};

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.GameplayTagAssetInterface.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* IGameplayTagAssetInterface::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.GameplayTagAssetInterface");
    return ptr;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.RemoveGameplayTag
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable
// RVA:    0x3E99110
// Params:
//   TagContainer                 0x000(0x020), Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   Tag                          0x020(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x028(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_RemoveGameplayTag(FGameplayTagContainer& TagContainer, FGameplayTag Tag)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.RemoveGameplayTag");

    UBlueprintGameplayTagLibrary_RemoveGameplayTag_Params params {};
    params.TagContainer = TagContainer;
    params.Tag = Tag;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.NotEqual_TagTag
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E98EA0
// Params:
//   A                            0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   B                            0x008(0x010), Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x018(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_NotEqual_TagTag(FGameplayTag A, const BasicTypes::FString& B)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.NotEqual_TagTag");

    UBlueprintGameplayTagLibrary_NotEqual_TagTag_Params params {};
    params.A = A;
    params.B = B;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.NotEqual_TagContainerTagContainer
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E98B70
// Params:
//   A                            0x000(0x020), Parm, NativeAccessSpecifierPublic
//   B                            0x020(0x010), Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x030(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_NotEqual_TagContainerTagContainer(FGameplayTagContainer A, const BasicTypes::FString& B)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.NotEqual_TagContainerTagContainer");

    UBlueprintGameplayTagLibrary_NotEqual_TagContainerTagContainer_Params params {};
    params.A = A;
    params.B = B;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.NotEqual_GameplayTagContainer
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E98920
// Params:
//   A                            0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   B                            0x020(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x040(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_NotEqual_GameplayTagContainer(const FGameplayTagContainer& A, const FGameplayTagContainer& B)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.NotEqual_GameplayTagContainer");

    UBlueprintGameplayTagLibrary_NotEqual_GameplayTagContainer_Params params {};
    params.A = A;
    params.B = B;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.NotEqual_GameplayTag
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E98750
// Params:
//   A                            0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   B                            0x008(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x010(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_NotEqual_GameplayTag(FGameplayTag A, FGameplayTag B)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.NotEqual_GameplayTag");

    UBlueprintGameplayTagLibrary_NotEqual_GameplayTag_Params params {};
    params.A = A;
    params.B = B;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MatchesTag
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E984C0
// Params:
//   TagOne                       0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   TagTwo                       0x008(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   bExactMatch                  0x010(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x011(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_MatchesTag(FGameplayTag TagOne, FGameplayTag TagTwo, bool bExactMatch)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MatchesTag");

    UBlueprintGameplayTagLibrary_MatchesTag_Params params {};
    params.TagOne = TagOne;
    params.TagTwo = TagTwo;
    params.bExactMatch = bExactMatch;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MatchesAnyTags
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E981D0
// Params:
//   TagOne                       0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   OtherContainer               0x008(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   bExactMatch                  0x028(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x029(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_MatchesAnyTags(FGameplayTag TagOne, const FGameplayTagContainer& OtherContainer, bool bExactMatch)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MatchesAnyTags");

    UBlueprintGameplayTagLibrary_MatchesAnyTags_Params params {};
    params.TagOne = TagOne;
    params.OtherContainer = OtherContainer;
    params.bExactMatch = bExactMatch;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeLiteralGameplayTagContainer
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E97EE0
// Params:
//   Value                        0x000(0x020), Parm, NativeAccessSpecifierPublic
//   ReturnValue                  0x020(0x020), Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic
FGameplayTagContainer UBlueprintGameplayTagLibrary::STATIC_MakeLiteralGameplayTagContainer(FGameplayTagContainer Value)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeLiteralGameplayTagContainer");

    UBlueprintGameplayTagLibrary_MakeLiteralGameplayTagContainer_Params params {};
    params.Value = Value;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeLiteralGameplayTag
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E97DC0
// Params:
//   Value                        0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x008), Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
FGameplayTag UBlueprintGameplayTagLibrary::STATIC_MakeLiteralGameplayTag(FGameplayTag Value)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeLiteralGameplayTag");

    UBlueprintGameplayTagLibrary_MakeLiteralGameplayTag_Params params {};
    params.Value = Value;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagQuery_MatchNoTags
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E97C20
// Params:
//   InTags                       0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x020(0x048), Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic
FGameplayTagQuery UBlueprintGameplayTagLibrary::STATIC_MakeGameplayTagQuery_MatchNoTags(const FGameplayTagContainer& InTags)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagQuery_MatchNoTags");

    UBlueprintGameplayTagLibrary_MakeGameplayTagQuery_MatchNoTags_Params params {};
    params.InTags = InTags;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagQuery_MatchAnyTags
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E97A80
// Params:
//   InTags                       0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x020(0x048), Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic
FGameplayTagQuery UBlueprintGameplayTagLibrary::STATIC_MakeGameplayTagQuery_MatchAnyTags(const FGameplayTagContainer& InTags)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagQuery_MatchAnyTags");

    UBlueprintGameplayTagLibrary_MakeGameplayTagQuery_MatchAnyTags_Params params {};
    params.InTags = InTags;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagQuery_MatchAllTags
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E978E0
// Params:
//   InTags                       0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x020(0x048), Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic
FGameplayTagQuery UBlueprintGameplayTagLibrary::STATIC_MakeGameplayTagQuery_MatchAllTags(const FGameplayTagContainer& InTags)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagQuery_MatchAllTags");

    UBlueprintGameplayTagLibrary_MakeGameplayTagQuery_MatchAllTags_Params params {};
    params.InTags = InTags;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagQuery
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E97590
// Params:
//   TagQuery                     0x000(0x048), Parm, NativeAccessSpecifierPublic
//   ReturnValue                  0x048(0x048), Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic
FGameplayTagQuery UBlueprintGameplayTagLibrary::STATIC_MakeGameplayTagQuery(FGameplayTagQuery TagQuery)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagQuery");

    UBlueprintGameplayTagLibrary_MakeGameplayTagQuery_Params params {};
    params.TagQuery = TagQuery;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagContainerFromTag
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E97290
// Params:
//   SingleTag                    0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x020), Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic
FGameplayTagContainer UBlueprintGameplayTagLibrary::STATIC_MakeGameplayTagContainerFromTag(FGameplayTag SingleTag)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagContainerFromTag");

    UBlueprintGameplayTagLibrary_MakeGameplayTagContainerFromTag_Params params {};
    params.SingleTag = SingleTag;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagContainerFromArray
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E97070
// Params:
//   GameplayTags                 0x000(0x010), Parm, ConstParm, OutParm, ReferenceParm, ZeroConstructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x010(0x020), Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic
FGameplayTagContainer UBlueprintGameplayTagLibrary::STATIC_MakeGameplayTagContainerFromArray(const BasicTypes::TArray<FGameplayTag>& GameplayTags)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.MakeGameplayTagContainerFromArray");

    UBlueprintGameplayTagLibrary_MakeGameplayTagContainerFromArray_Params params {};
    params.GameplayTags = GameplayTags;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.IsTagQueryEmpty
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E96EF0
// Params:
//   TagQuery                     0x000(0x048), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x048(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_IsTagQueryEmpty(const FGameplayTagQuery& TagQuery)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.IsTagQueryEmpty");

    UBlueprintGameplayTagLibrary_IsTagQueryEmpty_Params params {};
    params.TagQuery = TagQuery;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.IsGameplayTagValid
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E96DC0
// Params:
//   GameplayTag                  0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_IsGameplayTagValid(FGameplayTag GameplayTag)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.IsGameplayTagValid");

    UBlueprintGameplayTagLibrary_IsGameplayTagValid_Params params {};
    params.GameplayTag = GameplayTag;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.HasTag
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E96AA0
// Params:
//   TagContainer                 0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   Tag                          0x020(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   bExactMatch                  0x028(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x029(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_HasTag(const FGameplayTagContainer& TagContainer, FGameplayTag Tag, bool bExactMatch)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.HasTag");

    UBlueprintGameplayTagLibrary_HasTag_Params params {};
    params.TagContainer = TagContainer;
    params.Tag = Tag;
    params.bExactMatch = bExactMatch;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.HasAnyTags
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E966F0
// Params:
//   TagContainer                 0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   OtherContainer               0x020(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   bExactMatch                  0x040(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x041(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_HasAnyTags(const FGameplayTagContainer& TagContainer, const FGameplayTagContainer& OtherContainer, bool bExactMatch)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.HasAnyTags");

    UBlueprintGameplayTagLibrary_HasAnyTags_Params params {};
    params.TagContainer = TagContainer;
    params.OtherContainer = OtherContainer;
    params.bExactMatch = bExactMatch;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.HasAllTags
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E96340
// Params:
//   TagContainer                 0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   OtherContainer               0x020(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   bExactMatch                  0x040(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x041(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_HasAllTags(const FGameplayTagContainer& TagContainer, const FGameplayTagContainer& OtherContainer, bool bExactMatch)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.HasAllTags");

    UBlueprintGameplayTagLibrary_HasAllTags_Params params {};
    params.TagContainer = TagContainer;
    params.OtherContainer = OtherContainer;
    params.bExactMatch = bExactMatch;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.HasAllMatchingGameplayTags
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E960F0
// Params:
//   TagContainerInterface        0x000(0x010), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   OtherContainer               0x010(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x030(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_HasAllMatchingGameplayTags(const BasicTypes::TScriptInterface<IGameplayTagAssetInterface>& TagContainerInterface, const FGameplayTagContainer& OtherContainer)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.HasAllMatchingGameplayTags");

    UBlueprintGameplayTagLibrary_HasAllMatchingGameplayTags_Params params {};
    params.TagContainerInterface = TagContainerInterface;
    params.OtherContainer = OtherContainer;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetTagName
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E95FC0
// Params:
//   GameplayTag                  0x000(0x008), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x008), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
BasicTypes::FName UBlueprintGameplayTagLibrary::STATIC_GetTagName(const FGameplayTag& GameplayTag)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetTagName");

    UBlueprintGameplayTagLibrary_GetTagName_Params params {};
    params.GameplayTag = GameplayTag;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetOwnedGameplayTags
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E95DC0
// Params:
//   TagContainerInterface        0x000(0x010), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x010(0x020), Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic
FGameplayTagContainer UBlueprintGameplayTagLibrary::STATIC_GetOwnedGameplayTags(const BasicTypes::TScriptInterface<IGameplayTagAssetInterface>& TagContainerInterface)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetOwnedGameplayTags");

    UBlueprintGameplayTagLibrary_GetOwnedGameplayTags_Params params {};
    params.TagContainerInterface = TagContainerInterface;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetNumGameplayTagsInContainer
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E95C70
// Params:
//   TagContainer                 0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x020(0x004), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
int32_t UBlueprintGameplayTagLibrary::STATIC_GetNumGameplayTagsInContainer(const FGameplayTagContainer& TagContainer)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetNumGameplayTagsInContainer");

    UBlueprintGameplayTagLibrary_GetNumGameplayTagsInContainer_Params params {};
    params.TagContainer = TagContainer;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetDebugStringFromGameplayTagContainer
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E95AE0
// Params:
//   TagContainer                 0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x020(0x010), Parm, OutParm, ReturnParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
BasicTypes::FString UBlueprintGameplayTagLibrary::STATIC_GetDebugStringFromGameplayTagContainer(const FGameplayTagContainer& TagContainer)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetDebugStringFromGameplayTagContainer");

    UBlueprintGameplayTagLibrary_GetDebugStringFromGameplayTagContainer_Params params {};
    params.TagContainer = TagContainer;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetDebugStringFromGameplayTag
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E95970
// Params:
//   GameplayTag                  0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x010), Parm, OutParm, ReturnParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
BasicTypes::FString UBlueprintGameplayTagLibrary::STATIC_GetDebugStringFromGameplayTag(FGameplayTag GameplayTag)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetDebugStringFromGameplayTag");

    UBlueprintGameplayTagLibrary_GetDebugStringFromGameplayTag_Params params {};
    params.GameplayTag = GameplayTag;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetAllActorsOfClassMatchingTagQuery
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable
// RVA:    0x3E95600
// Params:
//   WorldContextObject           0x000(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ActorClass                   0x008(0x008), Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   GameplayTagQuery             0x010(0x048), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   OutActors                    0x058(0x010), Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic
void UBlueprintGameplayTagLibrary::STATIC_GetAllActorsOfClassMatchingTagQuery(CoreUObject::UObject* WorldContextObject, CoreUObject::UClass* ActorClass, const FGameplayTagQuery& GameplayTagQuery, BasicTypes::TArray<Engine::AActor*>& OutActors)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.GetAllActorsOfClassMatchingTagQuery");

    UBlueprintGameplayTagLibrary_GetAllActorsOfClassMatchingTagQuery_Params params {};
    params.WorldContextObject = WorldContextObject;
    params.ActorClass = ActorClass;
    params.GameplayTagQuery = GameplayTagQuery;
    params.OutActors = OutActors;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    OutActors = params.OutActors;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.EqualEqual_GameplayTagContainer
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E953C0
// Params:
//   A                            0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   B                            0x020(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x040(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_EqualEqual_GameplayTagContainer(const FGameplayTagContainer& A, const FGameplayTagContainer& B)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.EqualEqual_GameplayTagContainer");

    UBlueprintGameplayTagLibrary_EqualEqual_GameplayTagContainer_Params params {};
    params.A = A;
    params.B = B;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.EqualEqual_GameplayTag
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E951F0
// Params:
//   A                            0x000(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   B                            0x008(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x010(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_EqualEqual_GameplayTag(FGameplayTag A, FGameplayTag B)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.EqualEqual_GameplayTag");

    UBlueprintGameplayTagLibrary_EqualEqual_GameplayTag_Params params {};
    params.A = A;
    params.B = B;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.DoesTagAssetInterfaceHaveTag
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E94FF0
// Params:
//   TagContainerInterface        0x000(0x010), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   Tag                          0x010(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x018(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_DoesTagAssetInterfaceHaveTag(const BasicTypes::TScriptInterface<IGameplayTagAssetInterface>& TagContainerInterface, FGameplayTag Tag)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.DoesTagAssetInterfaceHaveTag");

    UBlueprintGameplayTagLibrary_DoesTagAssetInterfaceHaveTag_Params params {};
    params.TagContainerInterface = TagContainerInterface;
    params.Tag = Tag;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.DoesContainerMatchTagQuery
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E94D40
// Params:
//   TagContainer                 0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   TagQuery                     0x020(0x048), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   ReturnValue                  0x068(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool UBlueprintGameplayTagLibrary::STATIC_DoesContainerMatchTagQuery(const FGameplayTagContainer& TagContainer, const FGameplayTagQuery& TagQuery)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.DoesContainerMatchTagQuery");

    UBlueprintGameplayTagLibrary_DoesContainerMatchTagQuery_Params params {};
    params.TagContainer = TagContainer;
    params.TagQuery = TagQuery;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.Conv_ObjectToGameplayTagAssetInterface
// Flags:  Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure
// RVA:    0x3E94BD0
// Params:
//   InObject                     0x000(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x010), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic
BasicTypes::TScriptInterface<IGameplayTagAssetInterface> UBlueprintGameplayTagLibrary::STATIC_Conv_ObjectToGameplayTagAssetInterface(CoreUObject::UObject* InObject)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.Conv_ObjectToGameplayTagAssetInterface");

    UBlueprintGameplayTagLibrary_Conv_ObjectToGameplayTagAssetInterface_Params params {};
    params.InObject = InObject;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.BreakGameplayTagContainer
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable, BlueprintPure
// RVA:    0x3E949C0
// Params:
//   GameplayTagContainer         0x000(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   GameplayTags                 0x020(0x010), Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic
void UBlueprintGameplayTagLibrary::STATIC_BreakGameplayTagContainer(const FGameplayTagContainer& GameplayTagContainer, BasicTypes::TArray<FGameplayTag>& GameplayTags)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.BreakGameplayTagContainer");

    UBlueprintGameplayTagLibrary_BreakGameplayTagContainer_Params params {};
    params.GameplayTagContainer = GameplayTagContainer;
    params.GameplayTags = GameplayTags;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    GameplayTags = params.GameplayTags;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.AppendGameplayTagContainers
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable
// RVA:    0x3E94790
// Params:
//   InOutTagContainer            0x000(0x020), Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   InTagContainer               0x020(0x020), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
void UBlueprintGameplayTagLibrary::STATIC_AppendGameplayTagContainers(FGameplayTagContainer& InOutTagContainer, const FGameplayTagContainer& InTagContainer)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.AppendGameplayTagContainers");

    UBlueprintGameplayTagLibrary_AppendGameplayTagContainers_Params params {};
    params.InOutTagContainer = InOutTagContainer;
    params.InTagContainer = InTagContainer;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Script/GameplayTags.BlueprintGameplayTagLibrary.AddGameplayTag
// Flags:  Final, RequiredAPI, Native, Static, Public, HasOutParms, BlueprintCallable
// RVA:    0x3E94410
// Params:
//   TagContainer                 0x000(0x020), Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
//   Tag                          0x020(0x008), Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
void UBlueprintGameplayTagLibrary::STATIC_AddGameplayTag(FGameplayTagContainer& TagContainer, FGameplayTag Tag)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/GameplayTags.BlueprintGameplayTagLibrary.AddGameplayTag");

    UBlueprintGameplayTagLibrary_AddGameplayTag_Params params {};
    params.TagContainer = TagContainer;
    params.Tag = Tag;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.BlueprintGameplayTagLibrary.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UBlueprintGameplayTagLibrary::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.BlueprintGameplayTagLibrary");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.EditableGameplayTagQuery.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UEditableGameplayTagQuery::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.EditableGameplayTagQuery");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.EditableGameplayTagQueryExpression.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UEditableGameplayTagQueryExpression::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.EditableGameplayTagQueryExpression");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.GameplayTagsDeveloperSettings.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UGameplayTagsDeveloperSettings::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.GameplayTagsDeveloperSettings");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.GameplayTagsList.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UGameplayTagsList::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.GameplayTagsList");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.GameplayTagsManager.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UGameplayTagsManager::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.GameplayTagsManager");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.RestrictedGameplayTagsList.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* URestrictedGameplayTagsList::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.RestrictedGameplayTagsList");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.EditableGameplayTagQueryExpression_AllExprMatch.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UEditableGameplayTagQueryExpression_AllExprMatch::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.EditableGameplayTagQueryExpression_AllExprMatch");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.EditableGameplayTagQueryExpression_AllTagsMatch.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UEditableGameplayTagQueryExpression_AllTagsMatch::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.EditableGameplayTagQueryExpression_AllTagsMatch");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.EditableGameplayTagQueryExpression_AnyExprMatch.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UEditableGameplayTagQueryExpression_AnyExprMatch::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.EditableGameplayTagQueryExpression_AnyExprMatch");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.EditableGameplayTagQueryExpression_AnyTagsMatch.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UEditableGameplayTagQueryExpression_AnyTagsMatch::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.EditableGameplayTagQueryExpression_AnyTagsMatch");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.EditableGameplayTagQueryExpression_NoExprMatch.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UEditableGameplayTagQueryExpression_NoExprMatch::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.EditableGameplayTagQueryExpression_NoExprMatch");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.EditableGameplayTagQueryExpression_NoTagsMatch.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UEditableGameplayTagQueryExpression_NoTagsMatch::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.EditableGameplayTagQueryExpression_NoTagsMatch");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/GameplayTags.GameplayTagsSettings.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UGameplayTagsSettings::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/GameplayTags.GameplayTagsSettings");
    return ptr;
}
}

