// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/Engine_CLASSES.h"
#include "Headers/Inject_Impacts_CLASSES.h"
#include "Headers/Inject_Impacts_PARAMETERS.h"
#include "Headers/ShooterGame_CLASSES.h"

namespace CG::Inject_Impacts
{
// Name:   PredefinedFunction BlueprintGeneratedClass /Game/Packs/Steampunk/Weapons/GeneScanner/Inject_Impacts.Inject_Impacts_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* AInject_Impacts_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/Packs/Steampunk/Weapons/GeneScanner/Inject_Impacts.Inject_Impacts_C");
    return ptr;
}
}

