// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/OnlineSubsystemSteam_CLASSES.h"
#include "Headers/OnlineSubsystemSteam_PARAMETERS.h"
#include "Headers/OnlineSubsystemUtils_CLASSES.h"
#include "Headers/PacketHandler_CLASSES.h"

namespace CG::OnlineSubsystemSteam
{
// Name:   PredefinedFunction Class /Script/OnlineSubsystemSteam.SteamAuthComponentModuleInterface.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* USteamAuthComponentModuleInterface::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/OnlineSubsystemSteam.SteamAuthComponentModuleInterface");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/OnlineSubsystemSteam.SteamNetConnection.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* USteamNetConnection::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/OnlineSubsystemSteam.SteamNetConnection");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/OnlineSubsystemSteam.SteamNetDriver.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* USteamNetDriver::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/OnlineSubsystemSteam.SteamNetDriver");
    return ptr;
}
}

