// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/AC_FaceCustomization_CLASSES.h"
#include "Headers/BP_PrimalWindSourceComponent_Base_CLASSES.h"
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/CoreUObject_STRUCTS.h"
#include "Headers/Engine_CLASSES.h"
#include "Headers/Engine_STRUCTS.h"
#include "Headers/Enum_VoiceCollectionLine_ENUMS.h"
#include "Headers/NS_DinoFootprint_BP_CLASSES.h"
#include "Headers/PDA_VoiceCollection_CLASSES.h"
#include "Headers/PlayerPawnTest_CLASSES.h"
#include "Headers/PlayerPawnTest_PARAMETERS.h"
#include "Headers/ShooterGame_CLASSES.h"
#include "Headers/ShooterGame_STRUCTS.h"

namespace CG::PlayerPawnTest
{
// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.OnBossfightTeleport
// Flags:  Public, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   DataName                     0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::OnBossfightTeleport(const BasicTypes::FName& DataName)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.OnBossfightTeleport");

    APlayerPawnTest_C_OnBossfightTeleport_Params params {};
    params.DataName = DataName;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPGetCustomBlueprintData
// Flags:  Event, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   DataName                     0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   InData                       0x008(0x078), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
//   OutData                      0x080(0x078), Parm, OutParm
//   ReturnValue                  0x0F8(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool APlayerPawnTest_C::BPGetCustomBlueprintData(const BasicTypes::FName& DataName, const Engine::FBPNetExecParams& InData, Engine::FBPNetExecParams& OutData)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPGetCustomBlueprintData");

    APlayerPawnTest_C_BPGetCustomBlueprintData_Params params {};
    params.DataName = DataName;
    params.InData = InData;
    params.OutData = OutData;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    OutData = params.OutData;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPCustomRequest
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   RequestName                  0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   OutIndex                     0x008(0x004), Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   InIndex                      0x00C(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   FromActor                    0x010(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
//   ReturnValue                  0x018(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool APlayerPawnTest_C::BPCustomRequest(const BasicTypes::FName& RequestName, int32_t& OutIndex, int32_t InIndex, Engine::AActor* FromActor)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPCustomRequest");

    APlayerPawnTest_C_BPCustomRequest_Params params {};
    params.RequestName = RequestName;
    params.OutIndex = OutIndex;
    params.InIndex = InIndex;
    params.FromActor = FromActor;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    OutIndex = params.OutIndex;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.PlayVOLine
// Flags:  Public, BlueprintCallable, BlueprintEvent, Const
// RVA:    0x17D3880
// Params:
//   Voiceline                    0x000(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   VolumeMultiplier             0x008(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::PlayVOLine(Enum_VoiceCollectionLine::Enum_VoiceCollectionLine Voiceline, double VolumeMultiplier) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.PlayVOLine");

    APlayerPawnTest_C_PlayVOLine_Params params {};
    params.Voiceline = Voiceline;
    params.VolumeMultiplier = VolumeMultiplier;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.SelectVOSound
// Flags:  Public, HasOutParms, BlueprintCallable, BlueprintEvent, Const
// RVA:    0x17D3880
// Params:
//   VoiceCollection              0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
//   VoiceLineSelection           0x008(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   VoiceSoundReference          0x010(0x008), Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::SelectVOSound(PDA_VoiceCollection::UPDA_VoiceCollection_C* VoiceCollection, Enum_VoiceCollectionLine::Enum_VoiceCollectionLine VoiceLineSelection, Engine::USoundBase*& VoiceSoundReference) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.SelectVOSound");

    APlayerPawnTest_C_SelectVOSound_Params params {};
    params.VoiceCollection = VoiceCollection;
    params.VoiceLineSelection = VoiceLineSelection;
    params.VoiceSoundReference = VoiceSoundReference;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    VoiceSoundReference = params.VoiceSoundReference;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.UpdateFace
// Flags:  Public, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::UpdateFace()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.UpdateFace");

    APlayerPawnTest_C_UpdateFace_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPApplyBodyColors
// Flags:  Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   toMesh                       0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::BPApplyBodyColors(Engine::USkeletalMeshComponent* toMesh)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPApplyBodyColors");

    APlayerPawnTest_C_BPApplyBodyColors_Params params {};
    params.toMesh = toMesh;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPUnlockedAllBTTExplorerNotes
// Flags:  Event, Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   exp                          0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::BPUnlockedAllBTTExplorerNotes(int32_t exp)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPUnlockedAllBTTExplorerNotes");

    APlayerPawnTest_C_BPUnlockedAllBTTExplorerNotes_Params params {};
    params.exp = exp;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraDesiredPivotLocation
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   CurrentCameraPivotLocation   0x000(0x018), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   DesiredCameraPivotLocation   0x018(0x018), BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   ReturnValue                  0x030(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool APlayerPawnTest_C::BPOverrideCameraDesiredPivotLocation(CoreUObject::FVector CurrentCameraPivotLocation, CoreUObject::FVector& DesiredCameraPivotLocation)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraDesiredPivotLocation");

    APlayerPawnTest_C_BPOverrideCameraDesiredPivotLocation_Params params {};
    params.CurrentCameraPivotLocation = CurrentCameraPivotLocation;
    params.DesiredCameraPivotLocation = DesiredCameraPivotLocation;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.GetFXBloodColor
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   ReturnValue                  0x000(0x010), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
CoreUObject::FLinearColor APlayerPawnTest_C::GetFXBloodColor()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.GetFXBloodColor");

    APlayerPawnTest_C_GetFXBloodColor_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.DisableFluidInteraction
// Flags:  Exec, Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::DisableFluidInteraction()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.DisableFluidInteraction");

    APlayerPawnTest_C_DisableFluidInteraction_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.EnableFluidInteraction
// Flags:  Exec, Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::EnableFluidInteraction()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.EnableFluidInteraction");

    APlayerPawnTest_C_EnableFluidInteraction_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.AssignAssetsFromVoiceCollection
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::AssignAssetsFromVoiceCollection()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.AssignAssetsFromVoiceCollection");

    APlayerPawnTest_C_AssignAssetsFromVoiceCollection_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraDesiredPivotRotation
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   CurrentCameraPivotRotation   0x000(0x018), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor
//   DesiredCameraPivotRotation   0x018(0x018), BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ZeroConstructor, IsPlainOldData, NoDestructor
//   ReturnValue                  0x030(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool APlayerPawnTest_C::BPOverrideCameraDesiredPivotRotation(CoreUObject::FRotator CurrentCameraPivotRotation, CoreUObject::FRotator& DesiredCameraPivotRotation)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraDesiredPivotRotation");

    APlayerPawnTest_C_BPOverrideCameraDesiredPivotRotation_Params params {};
    params.CurrentCameraPivotRotation = CurrentCameraPivotRotation;
    params.DesiredCameraPivotRotation = DesiredCameraPivotRotation;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraDesiredPivotOffset
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   CameraParams                 0x000(0x0D8), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
//   DesiredCameraOffset          0x0D8(0x018), BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   ReturnValue                  0x0F0(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool APlayerPawnTest_C::BPOverrideCameraDesiredPivotOffset(const ShooterGame::FPrimalCameraParams& CameraParams, CoreUObject::FVector& DesiredCameraOffset)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraDesiredPivotOffset");

    APlayerPawnTest_C_BPOverrideCameraDesiredPivotOffset_Params params {};
    params.CameraParams = CameraParams;
    params.DesiredCameraOffset = DesiredCameraOffset;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraPivotLocationInterpParams
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   CameraParams                 0x000(0x0D8), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
//   PivotZInterpOverrides        0x0D8(0x034), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm, NoDestructor
//   LastInterpParamsX            0x10C(0x00C), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm, NoDestructor
//   LastInterpParamsY            0x118(0x00C), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm, NoDestructor
//   LastInterpParamsZ            0x124(0x00C), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm, NoDestructor
//   OutInterpParamsX             0x130(0x00C), BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor
//   OutInterpParamsY             0x13C(0x00C), BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor
//   OutInterpParamsZ             0x148(0x00C), BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor
//   ReturnValue                  0x154(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool APlayerPawnTest_C::BPOverrideCameraPivotLocationInterpParams(const ShooterGame::FPrimalCameraParams& CameraParams, const ShooterGame::FPrimalCameraPivotZInterpOverrides& PivotZInterpOverrides, const ShooterGame::FPrimalCameraInterpParams& LastInterpParamsX, const ShooterGame::FPrimalCameraInterpParams& LastInterpParamsY, const ShooterGame::FPrimalCameraInterpParams& LastInterpParamsZ, ShooterGame::FPrimalCameraInterpParams& OutInterpParamsX, ShooterGame::FPrimalCameraInterpParams& OutInterpParamsY, ShooterGame::FPrimalCameraInterpParams& OutInterpParamsZ)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraPivotLocationInterpParams");

    APlayerPawnTest_C_BPOverrideCameraPivotLocationInterpParams_Params params {};
    params.CameraParams = CameraParams;
    params.PivotZInterpOverrides = PivotZInterpOverrides;
    params.LastInterpParamsX = LastInterpParamsX;
    params.LastInterpParamsY = LastInterpParamsY;
    params.LastInterpParamsZ = LastInterpParamsZ;
    params.OutInterpParamsX = OutInterpParamsX;
    params.OutInterpParamsY = OutInterpParamsY;
    params.OutInterpParamsZ = OutInterpParamsZ;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraArmLengthInterpParams
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   CameraParams                 0x000(0x0D8), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
//   OutInterpParams              0x0D8(0x00C), BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor
//   ReturnValue                  0x0E4(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool APlayerPawnTest_C::BPOverrideCameraArmLengthInterpParams(const ShooterGame::FPrimalCameraParams& CameraParams, ShooterGame::FPrimalCameraInterpParams& OutInterpParams)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraArmLengthInterpParams");

    APlayerPawnTest_C_BPOverrideCameraArmLengthInterpParams_Params params {};
    params.CameraParams = CameraParams;
    params.OutInterpParams = OutInterpParams;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraArmLength
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   CameraParams                 0x000(0x0D8), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
//   CurrentCameraArmLength       0x0D8(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   DesiredCameraArmLength       0x0DC(0x004), BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   ReturnValue                  0x0E0(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool APlayerPawnTest_C::BPOverrideCameraArmLength(const ShooterGame::FPrimalCameraParams& CameraParams, float CurrentCameraArmLength, float& DesiredCameraArmLength)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPOverrideCameraArmLength");

    APlayerPawnTest_C_BPOverrideCameraArmLength_Params params {};
    params.CameraParams = CameraParams;
    params.CurrentCameraArmLength = CurrentCameraArmLength;
    params.DesiredCameraArmLength = DesiredCameraArmLength;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.DontCreateAnyMoreSpawnUIs
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::DontCreateAnyMoreSpawnUIs()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.DontCreateAnyMoreSpawnUIs");

    APlayerPawnTest_C_DontCreateAnyMoreSpawnUIs_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.GetShooterHud
// Flags:  Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   ShooterHUD                   0x000(0x008), Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::GetShooterHud(ShooterGame::AShooterHUD*& ShooterHUD)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.GetShooterHud");

    APlayerPawnTest_C_GetShooterHud_Params params {};
    params.ShooterHUD = ShooterHUD;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    ShooterHUD = params.ShooterHUD;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.SetGeneralizedUnlockedAchievementTags
// Flags:  Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   GeneralizedUnlockedAchievementTags 0x000(0x010), BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm
void APlayerPawnTest_C::SetGeneralizedUnlockedAchievementTags(BasicTypes::TArray<BasicTypes::FName>& GeneralizedUnlockedAchievementTags)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.SetGeneralizedUnlockedAchievementTags");

    APlayerPawnTest_C_SetGeneralizedUnlockedAchievementTags_Params params {};
    params.GeneralizedUnlockedAchievementTags = GeneralizedUnlockedAchievementTags;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.HasEquipToHideImplant
// Flags:  Public, HasOutParms, BlueprintCallable, BlueprintEvent, BlueprintPure
// RVA:    0x17D3880
// Params:
//   ShouldHideImplant            0x000(0x001), Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::HasEquipToHideImplant(bool ShouldHideImplant)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.HasEquipToHideImplant");

    APlayerPawnTest_C_HasEquipToHideImplant_Params params {};
    params.ShouldHideImplant = ShouldHideImplant;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPSetupFirstPersonHandsMesh
// Flags:  Event, Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::BPSetupFirstPersonHandsMesh()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPSetupFirstPersonHandsMesh");

    APlayerPawnTest_C_BPSetupFirstPersonHandsMesh_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.SetupMeshes
// Flags:  Public, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   bForce                       0x000(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::SetupMeshes(bool bForce)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.SetupMeshes");

    APlayerPawnTest_C_SetupMeshes_Params params {};
    params.bForce = bForce;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPUnlockedAllExplorerNotes
// Flags:  Event, Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::BPUnlockedAllExplorerNotes()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPUnlockedAllExplorerNotes");

    APlayerPawnTest_C_BPUnlockedAllExplorerNotes_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.GetTheNumChibiLevelUps
// Flags:  Public, HasOutParms, BlueprintCallable, BlueprintEvent, BlueprintPure
// RVA:    0x17D3880
// Params:
//   OutVal                       0x000(0x004), Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::GetTheNumChibiLevelUps(int32_t& OutVal)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.GetTheNumChibiLevelUps");

    APlayerPawnTest_C_GetTheNumChibiLevelUps_Params params {};
    params.OutVal = OutVal;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    OutVal = params.OutVal;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.SetNumChibiLevelUps
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   NewNum                       0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::SetNumChibiLevelUps(int32_t NewNum)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.SetNumChibiLevelUps");

    APlayerPawnTest_C_SetNumChibiLevelUps_Params params {};
    params.NewNum = NewNum;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPGetPlayerHexagonCount
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   ReturnValue                  0x000(0x004), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
int32_t APlayerPawnTest_C::BPGetPlayerHexagonCount()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPGetPlayerHexagonCount");

    APlayerPawnTest_C_BPGetPlayerHexagonCount_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPSetPlayerHexagonCount
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   NewHexagonCount              0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   ReturnValue                  0x004(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
bool APlayerPawnTest_C::BPSetPlayerHexagonCount(int32_t NewHexagonCount)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPSetPlayerHexagonCount");

    APlayerPawnTest_C_BPSetPlayerHexagonCount_Params params {};
    params.NewHexagonCount = NewHexagonCount;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPGetShowDebugAnimationComponents
// Flags:  Event, Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   SkelMeshComponents           0x000(0x010), Parm, OutParm, ContainsInstancedReference
void APlayerPawnTest_C::BPGetShowDebugAnimationComponents(BasicTypes::TArray<Engine::USkeletalMeshComponent*>& SkelMeshComponents)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPGetShowDebugAnimationComponents");

    APlayerPawnTest_C_BPGetShowDebugAnimationComponents_Params params {};
    params.SkelMeshComponents = SkelMeshComponents;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    SkelMeshComponents = params.SkelMeshComponents;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPGetOverrideCameraInterpSpeed
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   DefaultTPVCameraSpeedInterpolationMultiplier 0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   DefaultTPVOffsetInterpSpeed  0x004(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   TPVCameraSpeedInterpolationMultiplier 0x008(0x004), Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   TPVOffsetInterpSpeed         0x00C(0x004), Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::BPGetOverrideCameraInterpSpeed(float DefaultTPVCameraSpeedInterpolationMultiplier, float DefaultTPVOffsetInterpSpeed, float& TPVCameraSpeedInterpolationMultiplier, float& TPVOffsetInterpSpeed)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPGetOverrideCameraInterpSpeed");

    APlayerPawnTest_C_BPGetOverrideCameraInterpSpeed_Params params {};
    params.DefaultTPVCameraSpeedInterpolationMultiplier = DefaultTPVCameraSpeedInterpolationMultiplier;
    params.DefaultTPVOffsetInterpSpeed = DefaultTPVOffsetInterpSpeed;
    params.TPVCameraSpeedInterpolationMultiplier = TPVCameraSpeedInterpolationMultiplier;
    params.TPVOffsetInterpSpeed = TPVOffsetInterpSpeed;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    TPVCameraSpeedInterpolationMultiplier = params.TPVCameraSpeedInterpolationMultiplier;
    TPVOffsetInterpSpeed = params.TPVOffsetInterpSpeed;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ShowHUDNotification
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   Text                         0x000(0x010), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
//   Color                        0x010(0x010), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   LifetimeSeconds              0x020(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   DisplayScale                 0x028(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   SoundToPlay                  0x030(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::ShowHUDNotification(const BasicTypes::FString& Text, CoreUObject::FLinearColor Color, double LifetimeSeconds, double DisplayScale, Engine::USoundCue* SoundToPlay)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ShowHUDNotification");

    APlayerPawnTest_C_ShowHUDNotification_Params params {};
    params.Text = Text;
    params.Color = Color;
    params.LifetimeSeconds = LifetimeSeconds;
    params.DisplayScale = DisplayScale;
    params.SoundToPlay = SoundToPlay;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.TrySpawnMound
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::TrySpawnMound()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.TrySpawnMound");

    APlayerPawnTest_C_TrySpawnMound_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.TrySpawnMoundEx
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   Angle                        0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   Range                        0x008(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::TrySpawnMoundEx(double Angle, double Range)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.TrySpawnMoundEx");

    APlayerPawnTest_C_TrySpawnMoundEx_Params params {};
    params.Angle = Angle;
    params.Range = Range;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPSetFirstPersonMasterPoseComponent
// Flags:  Event, Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   firstPersonMasterPosecomponent 0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::BPSetFirstPersonMasterPoseComponent(Engine::USkeletalMeshComponent* firstPersonMasterPosecomponent)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPSetFirstPersonMasterPoseComponent");

    APlayerPawnTest_C_BPSetFirstPersonMasterPoseComponent_Params params {};
    params.firstPersonMasterPosecomponent = firstPersonMasterPosecomponent;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.DefeatedBoss
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   BossCharacter                0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
//   BossTag                      0x008(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   BossDifficulty               0x010(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::DefeatedBoss(ShooterGame::APrimalDinoCharacter* BossCharacter, const BasicTypes::FName& BossTag, int32_t BossDifficulty)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.DefeatedBoss");

    APlayerPawnTest_C_DefeatedBoss_Params params {};
    params.BossCharacter = BossCharacter;
    params.BossTag = BossTag;
    params.BossDifficulty = BossDifficulty;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ServerAscend
// Flags:  Public, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   DifficultyIndex              0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   bImmediateAscend             0x004(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   bSuppressAchievements        0x005(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   bIsCheatAscend               0x006(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::ServerAscend(int32_t DifficultyIndex, bool bImmediateAscend, bool bSuppressAchievements, bool bIsCheatAscend)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ServerAscend");

    APlayerPawnTest_C_ServerAscend_Params params {};
    params.DifficultyIndex = DifficultyIndex;
    params.bImmediateAscend = bImmediateAscend;
    params.bSuppressAchievements = bSuppressAchievements;
    params.bIsCheatAscend = bIsCheatAscend;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.PlayerCommand
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   TheCommand                   0x000(0x010), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
//   ReturnValue                  0x010(0x010), Parm, OutParm, ReturnParm, ZeroConstructor, HasGetValueTypeHash
BasicTypes::FString APlayerPawnTest_C::PlayerCommand(const BasicTypes::FString& TheCommand)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.PlayerCommand");

    APlayerPawnTest_C_PlayerCommand_Params params {};
    params.TheCommand = TheCommand;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.UserConstructionScript
// Flags:  Event, Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::UserConstructionScript()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.UserConstructionScript");

    APlayerPawnTest_C_UserConstructionScript_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ReceiveBeginPlay
// Flags:  Event, Protected, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::ReceiveBeginPlay()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ReceiveBeginPlay");

    APlayerPawnTest_C_ReceiveBeginPlay_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.NetClientAscend
// Flags:  Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   AscendIndex                  0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   bImmediateAscend             0x004(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   bIsCheatAscend               0x005(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::NetClientAscend(int32_t AscendIndex, bool bImmediateAscend, bool bIsCheatAscend)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.NetClientAscend");

    APlayerPawnTest_C_NetClientAscend_Params params {};
    params.AscendIndex = AscendIndex;
    params.bImmediateAscend = bImmediateAscend;
    params.bIsCheatAscend = bIsCheatAscend;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ClientShowHUDNotification
// Flags:  Net, NetClient, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   Text                         0x000(0x010), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
//   Color                        0x010(0x010), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   LifetimeSeconds              0x020(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   DisplayScale                 0x028(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   SoundToPlay                  0x030(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::ClientShowHUDNotification(const BasicTypes::FString& Text, CoreUObject::FLinearColor Color, double LifetimeSeconds, double DisplayScale, Engine::USoundCue* SoundToPlay)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ClientShowHUDNotification");

    APlayerPawnTest_C_ClientShowHUDNotification_Params params {};
    params.Text = Text;
    params.Color = Color;
    params.LifetimeSeconds = LifetimeSeconds;
    params.DisplayScale = DisplayScale;
    params.SoundToPlay = SoundToPlay;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.NetClientPreLoadAcension
// Flags:  Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::NetClientPreLoadAcension()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.NetClientPreLoadAcension");

    APlayerPawnTest_C_NetClientPreLoadAcension_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPSpawnAttackerDamageImpactFX
// Flags:  Event, Public, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   SocketName                   0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   VictimChar                   0x008(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::BPSpawnAttackerDamageImpactFX(const BasicTypes::FName& SocketName, ShooterGame::APrimalCharacter* VictimChar)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPSpawnAttackerDamageImpactFX");

    APlayerPawnTest_C_BPSpawnAttackerDamageImpactFX_Params params {};
    params.SocketName = SocketName;
    params.VictimChar = VictimChar;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.AscensionCheck
// Flags:  BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void APlayerPawnTest_C::AscensionCheck()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.AscensionCheck");

    APlayerPawnTest_C_AscensionCheck_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.InterceptInputEvent
// Flags:  Event, Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   InputName                    0x000(0x010), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash
void APlayerPawnTest_C::InterceptInputEvent(const BasicTypes::FString& InputName)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.InterceptInputEvent");

    APlayerPawnTest_C_InterceptInputEvent_Params params {};
    params.InputName = InputName;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPApplyPreviewData
// Flags:  Event, Public, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   toMesh                       0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::BPApplyPreviewData(Engine::USkeletalMeshComponent* toMesh)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.BPApplyPreviewData");

    APlayerPawnTest_C_BPApplyPreviewData_Params params {};
    params.toMesh = toMesh;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ExecuteUbergraph_PlayerPawnTest
// Flags:  Final, UberGraphFunction, HasDefaults
// RVA:    0x17D3880
// Params:
//   EntryPoint                   0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void APlayerPawnTest_C::ExecuteUbergraph_PlayerPawnTest(int32_t EntryPoint)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.ExecuteUbergraph_PlayerPawnTest");

    APlayerPawnTest_C_ExecuteUbergraph_PlayerPawnTest_Params params {};
    params.EntryPoint = EntryPoint;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* APlayerPawnTest_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/PlayerPawnTest.PlayerPawnTest_C");
    return ptr;
}
}

