// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/PrimalItemStructure_BaseFloor_CLASSES.h"
#include "Headers/PrimalItemStructure_TriFoundation_Stone_CLASSES.h"
#include "Headers/PrimalItemStructure_TriFoundation_Stone_PARAMETERS.h"

namespace CG::PrimalItemStructure_TriFoundation_Stone
{
// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/StructuresPlus/Structures/Foundations/Triangle/Stone/PrimalItemStructure_TriFoundation_Stone.PrimalItemStructure_TriFoundation_Stone_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UPrimalItemStructure_TriFoundation_Stone_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/StructuresPlus/Structures/Foundations/Triangle/Stone/PrimalItemStructure_TriFoundation_Stone.PrimalItemStructure_TriFoundation_Stone_C");
    return ptr;
}
}

