// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/PrimalItemResourceGeneric_ApexDrop_CLASSES.h"
#include "Headers/PrimalItemResourceGeneric_ApexDrop_PARAMETERS.h"
#include "Headers/PrimalItemResourceGeneric_CLASSES.h"

namespace CG::PrimalItemResourceGeneric_ApexDrop
{
// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResourceGeneric_ApexDrop.PrimalItemResourceGeneric_ApexDrop_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UPrimalItemResourceGeneric_ApexDrop_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResourceGeneric_ApexDrop.PrimalItemResourceGeneric_ApexDrop_C");
    return ptr;
}
}

