// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/PrimalItemArmor_DeinotheriumSaddle_ASA_CLASSES.h"
#include "Headers/PrimalItemArmor_DeinotheriumSaddle_ASA_PARAMETERS.h"
#include "Headers/PrimalItemArmor_SaddleGeneric_CLASSES.h"

namespace CG::PrimalItemArmor_DeinotheriumSaddle_ASA
{
// Name:   PredefinedFunction BlueprintGeneratedClass /Game/ASA/Dinos/Deinotherium/Dinos/Saddle/PrimalItemArmor_DeinotheriumSaddle_ASA.PrimalItemArmor_DeinotheriumSaddle_ASA_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UPrimalItemArmor_DeinotheriumSaddle_ASA_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/ASA/Dinos/Deinotherium/Dinos/Saddle/PrimalItemArmor_DeinotheriumSaddle_ASA.PrimalItemArmor_DeinotheriumSaddle_ASA_C");
    return ptr;
}
}

