// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/CoreUObject_STRUCTS.h"
#include "Headers/Engine_CLASSES.h"
#include "Headers/Engine_STRUCTS.h"
#include "Headers/PrimalItemArmorGeneric_CLASSES.h"
#include "Headers/PrimalItemArmor_Shield_CLASSES.h"
#include "Headers/PrimalItemArmor_Shield_PARAMETERS.h"
#include "Headers/ShooterGame_CLASSES.h"

namespace CG::PrimalItemArmor_Shield
{
// Name:   Function /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C.BPGetShieldHitImpactEffect
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   ReturnValue                  0x000(0x008), Parm, OutParm, ReturnParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
Engine::UFXSystemAsset* UPrimalItemArmor_Shield_C::BPGetShieldHitImpactEffect()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C.BPGetShieldHitImpactEffect");

    UPrimalItemArmor_Shield_C_BPGetShieldHitImpactEffect_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C.BPClientHandleItemNetExecCommand
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   CommandName                  0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   ExecParams                   0x008(0x078), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
//   ForPC                        0x080(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
void UPrimalItemArmor_Shield_C::BPClientHandleItemNetExecCommand(const BasicTypes::FName& CommandName, const Engine::FBPNetExecParams& ExecParams, ShooterGame::AShooterPlayerController* ForPC)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C.BPClientHandleItemNetExecCommand");

    UPrimalItemArmor_Shield_C_BPClientHandleItemNetExecCommand_Params params {};
    params.CommandName = CommandName;
    params.ExecParams = ExecParams;
    params.ForPC = ForPC;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C.PlayHitShieldEffect
// Flags:  Public, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   LocalOnly                    0x000(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   HitLoc                       0x008(0x018), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   FromLoc                      0x020(0x018), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void UPrimalItemArmor_Shield_C::PlayHitShieldEffect(bool LocalOnly, CoreUObject::FVector HitLoc, CoreUObject::FVector FromLoc)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C.PlayHitShieldEffect");

    UPrimalItemArmor_Shield_C_PlayHitShieldEffect_Params params {};
    params.LocalOnly = LocalOnly;
    params.HitLoc = HitLoc;
    params.FromLoc = FromLoc;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C.HandleShieldDamageBlocking
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   ForShooterCharacter          0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
//   DamageIn                     0x008(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   DamageEvent                  0x010(0x020), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
//   EventInstigator              0x030(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
//   DamageCauser                 0x038(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
//   HitPoint                     0x040(0x018), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   ReturnValue                  0x058(0x004), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
float UPrimalItemArmor_Shield_C::HandleShieldDamageBlocking(ShooterGame::AShooterCharacter* ForShooterCharacter, float DamageIn, const Engine::FDamageEvent& DamageEvent, Engine::AController* EventInstigator, Engine::AActor* DamageCauser, CoreUObject::FVector HitPoint)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C.HandleShieldDamageBlocking");

    UPrimalItemArmor_Shield_C_HandleShieldDamageBlocking_Params params {};
    params.ForShooterCharacter = ForShooterCharacter;
    params.DamageIn = DamageIn;
    params.DamageEvent = DamageEvent;
    params.EventInstigator = EventInstigator;
    params.DamageCauser = DamageCauser;
    params.HitPoint = HitPoint;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UPrimalItemArmor_Shield_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield_C");
    return ptr;
}
}

