// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/Engine_STRUCTS.h"
#include "Headers/ShooterGame_CLASSES.h"
#include "Headers/SlateCore_STRUCTS.h"
#include "Headers/Slider_ASA_Widget_CLASSES.h"
#include "Headers/Slider_ASA_Widget_PARAMETERS.h"
#include "Headers/UMG_CLASSES.h"

namespace CG::Slider_ASA_Widget
{
// Name:   Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.GetOverrideHighligteableWidgetBP
// Flags:  Event, Public, HasOutParms, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   ReturnValue                  0x000(0x008), Parm, OutParm, ReturnParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash
UMG::UWidget* USlider_ASA_Widget_C::GetOverrideHighligteableWidgetBP()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.GetOverrideHighligteableWidgetBP");

    USlider_ASA_Widget_C_GetOverrideHighligteableWidgetBP_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.SetupSetPercent
// Flags:  Public, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   InputPin                     0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   PreventRecallParent          0x004(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void USlider_ASA_Widget_C::SetupSetPercent(float InputPin, bool PreventRecallParent)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.SetupSetPercent");

    USlider_ASA_Widget_C_SetupSetPercent_Params params {};
    params.InputPin = InputPin;
    params.PreventRecallParent = PreventRecallParent;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.SetupValue
// Flags:  BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   _float_                      0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   PreventRecallParent          0x008(0x001), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void USlider_ASA_Widget_C::SetupValue(double _float_, bool PreventRecallParent)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.SetupValue");

    USlider_ASA_Widget_C_SetupValue_Params params {};
    params._float_ = _float_;
    params.PreventRecallParent = PreventRecallParent;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.BPExecutedCommandForPrimalUI
// Flags:  Event, Public, HasOutParms, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   CommandName                  0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   ExecParams                   0x008(0x078), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm
void USlider_ASA_Widget_C::BPExecutedCommandForPrimalUI(const BasicTypes::FName& CommandName, const Engine::FBPNetExecParams& ExecParams)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.BPExecutedCommandForPrimalUI");

    USlider_ASA_Widget_C_BPExecutedCommandForPrimalUI_Params params {};
    params.CommandName = CommandName;
    params.ExecParams = ExecParams;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.Tick
// Flags:  BlueprintCosmetic, Event, Public, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   MyGeometry                   0x000(0x038), BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor
//   InDeltaTime                  0x038(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void USlider_ASA_Widget_C::Tick(SlateCore::FGeometry MyGeometry, float InDeltaTime)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.Tick");

    USlider_ASA_Widget_C_Tick_Params params {};
    params.MyGeometry = MyGeometry;
    params.InDeltaTime = InDeltaTime;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.ExecuteUbergraph_Slider_ASA_Widget
// Flags:  Final, UberGraphFunction, HasDefaults
// RVA:    0x17D3880
// Params:
//   EntryPoint                   0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void USlider_ASA_Widget_C::ExecuteUbergraph_Slider_ASA_Widget(int32_t EntryPoint)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.ExecuteUbergraph_Slider_ASA_Widget");

    USlider_ASA_Widget_C_ExecuteUbergraph_Slider_ASA_Widget_Params params {};
    params.EntryPoint = EntryPoint;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction WidgetBlueprintGeneratedClass /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* USlider_ASA_Widget_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("WidgetBlueprintGeneratedClass /Game/ASA/UI/Slider_ASA_Widget.Slider_ASA_Widget_C");
    return ptr;
}
}

