// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/CoreUObject_STRUCTS.h"
#include "Headers/Engine_CLASSES.h"
#include "Headers/Engine_ENUMS.h"
#include "Headers/Engine_STRUCTS.h"
#include "Headers/GameplayAbilities_CLASSES.h"
#include "Headers/GameplayAbilities_STRUCTS.h"
#include "Headers/TargetingSystem_CLASSES.h"
#include "Headers/TargetingSystem_ENUMS.h"
#include "Headers/TargetingSystem_PARAMETERS.h"
#include "Headers/TargetingSystem_STRUCTS.h"

namespace CG::TargetingSystem
{










// Name:   Function /Script/TargetingSystem.AbilityTask_PerformTargeting.PerformTargetingRequest
// Flags:  Final, Native, Static, Public, BlueprintCallable
// RVA:    0x9420AC0
// Params:
//   OwningAbility                0x000(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   InTargetingPreset            0x008(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   bAllowAsync                  0x010(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x018(0x008), Parm, OutParm, ReturnParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
UAbilityTask_PerformTargeting* UAbilityTask_PerformTargeting::STATIC_PerformTargetingRequest(GameplayAbilities::UGameplayAbility* OwningAbility, UTargetingPreset* InTargetingPreset, bool bAllowAsync)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.AbilityTask_PerformTargeting.PerformTargetingRequest");

    UAbilityTask_PerformTargeting_PerformTargetingRequest_Params params {};
    params.OwningAbility = OwningAbility;
    params.InTargetingPreset = InTargetingPreset;
    params.bAllowAsync = bAllowAsync;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.AbilityTask_PerformTargeting.PerformFilteringRequest
// Flags:  Final, Native, Static, Public, BlueprintCallable
// RVA:    0x9420750
// Params:
//   OwningAbility                0x000(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   TargetingPreset              0x008(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   InTargets                    0x010(0x010), Parm, ConstParm, ZeroConstructor, NativeAccessSpecifierPublic
//   bAllowAsync                  0x020(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x028(0x008), Parm, OutParm, ReturnParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
UAbilityTask_PerformTargeting* UAbilityTask_PerformTargeting::STATIC_PerformFilteringRequest(GameplayAbilities::UGameplayAbility* OwningAbility, UTargetingPreset* TargetingPreset, BasicTypes::TArray<Engine::AActor*> InTargets, bool bAllowAsync)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.AbilityTask_PerformTargeting.PerformFilteringRequest");

    UAbilityTask_PerformTargeting_PerformFilteringRequest_Params params {};
    params.OwningAbility = OwningAbility;
    params.TargetingPreset = TargetingPreset;
    params.InTargets = InTargets;
    params.bAllowAsync = bAllowAsync;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.AbilityTask_PerformTargeting.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UAbilityTask_PerformTargeting::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.AbilityTask_PerformTargeting");
    return ptr;
}

// Name:   Function /Script/TargetingSystem.AsyncAction_PerformTargeting.PerformTargetingRequest
// Flags:  Final, Native, Static, Public, BlueprintCallable
// RVA:    0x94214B0
// Params:
//   SourceActor                  0x000(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   TargetingPreset              0x008(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   bUseAsyncTargeting           0x010(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x018(0x008), Parm, OutParm, ReturnParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
UAsyncAction_PerformTargeting* UAsyncAction_PerformTargeting::STATIC_PerformTargetingRequest(Engine::AActor* SourceActor, UTargetingPreset* TargetingPreset, bool bUseAsyncTargeting)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.AsyncAction_PerformTargeting.PerformTargetingRequest");

    UAsyncAction_PerformTargeting_PerformTargetingRequest_Params params {};
    params.SourceActor = SourceActor;
    params.TargetingPreset = TargetingPreset;
    params.bUseAsyncTargeting = bUseAsyncTargeting;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.AsyncAction_PerformTargeting.PerformFilteringRequest
// Flags:  Final, Native, Static, Public, BlueprintCallable
// RVA:    0x9421060
// Params:
//   SourceActor                  0x000(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   TargetingPreset              0x008(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   bUseAsyncTargeting           0x010(0x001), Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   InTargets                    0x018(0x010), Parm, ConstParm, ZeroConstructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x028(0x008), Parm, OutParm, ReturnParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
UAsyncAction_PerformTargeting* UAsyncAction_PerformTargeting::STATIC_PerformFilteringRequest(Engine::AActor* SourceActor, UTargetingPreset* TargetingPreset, bool bUseAsyncTargeting, BasicTypes::TArray<Engine::AActor*> InTargets)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.AsyncAction_PerformTargeting.PerformFilteringRequest");

    UAsyncAction_PerformTargeting_PerformFilteringRequest_Params params {};
    params.SourceActor = SourceActor;
    params.TargetingPreset = TargetingPreset;
    params.bUseAsyncTargeting = bUseAsyncTargeting;
    params.InTargets = InTargets;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.AsyncAction_PerformTargeting.GetTargetingHandle
// Flags:  Final, Native, Public, BlueprintCallable, BlueprintPure, Const
// RVA:    0x9421000
// Params:
//   ReturnValue                  0x000(0x004), Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic
FTargetingRequestHandle UAsyncAction_PerformTargeting::GetTargetingHandle() const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.AsyncAction_PerformTargeting.GetTargetingHandle");

    UAsyncAction_PerformTargeting_GetTargetingHandle_Params params {};

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.AsyncAction_PerformTargeting.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UAsyncAction_PerformTargeting::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.AsyncAction_PerformTargeting");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingPreset.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingPreset::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingPreset");
    return ptr;
}

// Name:   Function /Script/TargetingSystem.TargetingSubsystem.StartAsyncTargetingRequest
// Flags:  Final, Native, Public, HasOutParms, BlueprintCallable
// RVA:    0x9426890
// Params:
//   TargetingPreset              0x000(0x008), Parm, ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   InSourceContext              0x008(0x038), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   CompletionDynamicDelegate    0x040(0x010), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x050(0x004), Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic
FTargetingRequestHandle UTargetingSubsystem::StartAsyncTargetingRequest(UTargetingPreset* TargetingPreset, const FTargetingSourceContext& InSourceContext, const BasicTypes::UScriptDelegate& CompletionDynamicDelegate)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSubsystem.StartAsyncTargetingRequest");

    UTargetingSubsystem_StartAsyncTargetingRequest_Params params {};
    params.TargetingPreset = TargetingPreset;
    params.InSourceContext = InSourceContext;
    params.CompletionDynamicDelegate = CompletionDynamicDelegate;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSubsystem.RemoveAsyncTargetingRequestWithHandle
// Flags:  Final, RequiredAPI, Native, Public, HasOutParms, BlueprintCallable
// RVA:    0x9426770
// Params:
//   TargetingHandle              0x000(0x004), Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
void UTargetingSubsystem::RemoveAsyncTargetingRequestWithHandle(FTargetingRequestHandle& TargetingHandle)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSubsystem.RemoveAsyncTargetingRequestWithHandle");

    UTargetingSubsystem_RemoveAsyncTargetingRequestWithHandle_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Script/TargetingSystem.TargetingSubsystem.OverrideCollisionQueryTaskData
// Flags:  Final, Native, Static, Public, HasOutParms, BlueprintCallable
// RVA:    0x9426530
// Params:
//   TargetingHandle              0x000(0x004), Parm, NoDestructor, NativeAccessSpecifierPublic
//   CollisionQueryDataOverride   0x008(0x010), Parm, ConstParm, OutParm, ReferenceParm, NativeAccessSpecifierPublic
void UTargetingSubsystem::STATIC_OverrideCollisionQueryTaskData(FTargetingRequestHandle TargetingHandle, const FCollisionQueryTaskData& CollisionQueryDataOverride)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSubsystem.OverrideCollisionQueryTaskData");

    UTargetingSubsystem_OverrideCollisionQueryTaskData_Params params {};
    params.TargetingHandle = TargetingHandle;
    params.CollisionQueryDataOverride = CollisionQueryDataOverride;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Script/TargetingSystem.TargetingSubsystem.GetTargetingSourceContext
// Flags:  Final, RequiredAPI, Native, Public, BlueprintCallable, BlueprintPure, Const
// RVA:    0x94262F0
// Params:
//   TargetingHandle              0x000(0x004), Parm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x038), Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic
FTargetingSourceContext UTargetingSubsystem::GetTargetingSourceContext(FTargetingRequestHandle TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSubsystem.GetTargetingSourceContext");

    UTargetingSubsystem_GetTargetingSourceContext_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSubsystem.GetTargetingResultsActors
// Flags:  Final, RequiredAPI, Native, Public, HasOutParms, BlueprintCallable, BlueprintPure, Const
// RVA:    0x94260A0
// Params:
//   TargetingHandle              0x000(0x004), Parm, NoDestructor, NativeAccessSpecifierPublic
//   Targets                      0x008(0x010), Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic
void UTargetingSubsystem::GetTargetingResultsActors(FTargetingRequestHandle TargetingHandle, BasicTypes::TArray<Engine::AActor*>& Targets) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSubsystem.GetTargetingResultsActors");

    UTargetingSubsystem_GetTargetingResultsActors_Params params {};
    params.TargetingHandle = TargetingHandle;
    params.Targets = Targets;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    Targets = params.Targets;
}

// Name:   Function /Script/TargetingSystem.TargetingSubsystem.GetTargetingResults
// Flags:  Final, RequiredAPI, Native, Public, HasOutParms, BlueprintCallable, BlueprintPure, Const
// RVA:    0x9425E60
// Params:
//   TargetingHandle              0x000(0x004), Parm, NoDestructor, NativeAccessSpecifierPublic
//   OutTargets                   0x008(0x010), Parm, OutParm, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic
void UTargetingSubsystem::GetTargetingResults(FTargetingRequestHandle TargetingHandle, BasicTypes::TArray<Engine::FHitResult>& OutTargets) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSubsystem.GetTargetingResults");

    UTargetingSubsystem_GetTargetingResults_Params params {};
    params.TargetingHandle = TargetingHandle;
    params.OutTargets = OutTargets;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    OutTargets = params.OutTargets;
}

// Name:   Function /Script/TargetingSystem.TargetingSubsystem.ExecuteTargetingRequest
// Flags:  Final, Native, Public, HasOutParms, BlueprintCallable
// RVA:    0x9425A70
// Params:
//   TargetingPreset              0x000(0x008), Parm, ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   InSourceContext              0x008(0x038), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   CompletionDynamicDelegate    0x040(0x010), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
void UTargetingSubsystem::ExecuteTargetingRequest(UTargetingPreset* TargetingPreset, const FTargetingSourceContext& InSourceContext, const BasicTypes::UScriptDelegate& CompletionDynamicDelegate)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSubsystem.ExecuteTargetingRequest");

    UTargetingSubsystem_ExecuteTargetingRequest_Params params {};
    params.TargetingPreset = TargetingPreset;
    params.InSourceContext = InSourceContext;
    params.CompletionDynamicDelegate = CompletionDynamicDelegate;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingSubsystem.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingSubsystem::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingSubsystem");
    return ptr;
}

// Name:   Function /Script/TargetingSystem.TargetingTask.GetTargetingSubsystem
// Flags:  Final, Native, Protected, HasOutParms, BlueprintCallable, BlueprintPure, Const
// RVA:    0x9427BC0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x008), Parm, OutParm, ReturnParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
UTargetingSubsystem* UTargetingTask::GetTargetingSubsystem(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingTask.GetTargetingSubsystem");

    UTargetingTask_GetTargetingSubsystem_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingTask.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingTask::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingTask");
    return ptr;
}

// Name:   Function /Script/TargetingSystem.SimpleTargetingSelectionTask.SelectTargets
// Flags:  Native, Event, Public, HasOutParms, BlueprintEvent, Const
// RVA:    0x9422C30
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   SourceContext                0x008(0x038), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
void USimpleTargetingSelectionTask::SelectTargets(const FTargetingRequestHandle& TargetingHandle, const FTargetingSourceContext& SourceContext) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.SimpleTargetingSelectionTask.SelectTargets");

    USimpleTargetingSelectionTask_SelectTargets_Params params {};
    params.TargetingHandle = TargetingHandle;
    params.SourceContext = SourceContext;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Script/TargetingSystem.SimpleTargetingSelectionTask.AddTargetActor
// Flags:  Final, Native, Protected, HasOutParms, BlueprintCallable, Const
// RVA:    0x94227F0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   Actor                        0x008(0x008), Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
//   ReturnValue                  0x010(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool USimpleTargetingSelectionTask::AddTargetActor(const FTargetingRequestHandle& TargetingHandle, Engine::AActor* Actor) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.SimpleTargetingSelectionTask.AddTargetActor");

    USimpleTargetingSelectionTask_AddTargetActor_Params params {};
    params.TargetingHandle = TargetingHandle;
    params.Actor = Actor;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.SimpleTargetingSelectionTask.AddHitResult
// Flags:  Final, Native, Protected, HasOutParms, BlueprintCallable, Const
// RVA:    0x94223C0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   HitResult                    0x008(0x108), Parm, ConstParm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic
//   ReturnValue                  0x110(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool USimpleTargetingSelectionTask::AddHitResult(const FTargetingRequestHandle& TargetingHandle, const Engine::FHitResult& HitResult) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.SimpleTargetingSelectionTask.AddHitResult");

    USimpleTargetingSelectionTask_AddHitResult_Params params {};
    params.TargetingHandle = TargetingHandle;
    params.HitResult = HitResult;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.SimpleTargetingSelectionTask.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* USimpleTargetingSelectionTask::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.SimpleTargetingSelectionTask");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingFilterTask_BasicFilterTemplate.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingFilterTask_BasicFilterTemplate::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingFilterTask_BasicFilterTemplate");
    return ptr;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_AOE.GetSourceRotation
// Flags:  Native, Event, Protected, HasOutParms, HasDefaults, BlueprintEvent, Const
// RVA:    0x9423CF0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x010(0x020), Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
CoreUObject::FQuat UTargetingSelectionTask_AOE::GetSourceRotation(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_AOE.GetSourceRotation");

    UTargetingSelectionTask_AOE_GetSourceRotation_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_AOE.GetSourceOffset
// Flags:  Native, Event, Protected, HasOutParms, HasDefaults, BlueprintEvent, Const
// RVA:    0x9423AB0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x018), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
CoreUObject::FVector UTargetingSelectionTask_AOE::GetSourceOffset(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_AOE.GetSourceOffset");

    UTargetingSelectionTask_AOE_GetSourceOffset_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_AOE.GetSourceLocation
// Flags:  Native, Event, Protected, HasOutParms, HasDefaults, BlueprintEvent, Const
// RVA:    0x9423870
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x018), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
CoreUObject::FVector UTargetingSelectionTask_AOE::GetSourceLocation(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_AOE.GetSourceLocation");

    UTargetingSelectionTask_AOE_GetSourceLocation_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingSelectionTask_AOE.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingSelectionTask_AOE::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingSelectionTask_AOE");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingSelectionTask_SourceActor.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingSelectionTask_SourceActor::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingSelectionTask_SourceActor");
    return ptr;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetTraceLength
// Flags:  Native, Event, Protected, HasOutParms, BlueprintEvent, Const
// RVA:    0x94255F0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x004(0x004), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
float UTargetingSelectionTask_Trace::GetTraceLength(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetTraceLength");

    UTargetingSelectionTask_Trace_GetTraceLength_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetTraceDirection
// Flags:  Native, Event, Protected, HasOutParms, HasDefaults, BlueprintEvent, Const
// RVA:    0x94253D0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x018), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
CoreUObject::FVector UTargetingSelectionTask_Trace::GetTraceDirection(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetTraceDirection");

    UTargetingSelectionTask_Trace_GetTraceDirection_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSweptTraceRotation
// Flags:  Native, Event, Protected, HasOutParms, HasDefaults, BlueprintEvent, Const
// RVA:    0x9425190
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x018), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic
CoreUObject::FRotator UTargetingSelectionTask_Trace::GetSweptTraceRotation(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSweptTraceRotation");

    UTargetingSelectionTask_Trace_GetSweptTraceRotation_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSweptTraceRadius
// Flags:  Native, Event, Protected, HasOutParms, BlueprintEvent, Const
// RVA:    0x9425060
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x004(0x004), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
float UTargetingSelectionTask_Trace::GetSweptTraceRadius(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSweptTraceRadius");

    UTargetingSelectionTask_Trace_GetSweptTraceRadius_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSweptTraceCapsuleHalfHeight
// Flags:  Native, Event, Protected, HasOutParms, BlueprintEvent, Const
// RVA:    0x9424E50
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x004(0x004), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
float UTargetingSelectionTask_Trace::GetSweptTraceCapsuleHalfHeight(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSweptTraceCapsuleHalfHeight");

    UTargetingSelectionTask_Trace_GetSweptTraceCapsuleHalfHeight_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSweptTraceBoxHalfExtents
// Flags:  Native, Event, Protected, HasOutParms, HasDefaults, BlueprintEvent, Const
// RVA:    0x9424C30
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x018), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
CoreUObject::FVector UTargetingSelectionTask_Trace::GetSweptTraceBoxHalfExtents(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSweptTraceBoxHalfExtents");

    UTargetingSelectionTask_Trace_GetSweptTraceBoxHalfExtents_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSourceOffset
// Flags:  Native, Event, Protected, HasOutParms, HasDefaults, BlueprintEvent, Const
// RVA:    0x94249F0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x018), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
CoreUObject::FVector UTargetingSelectionTask_Trace::GetSourceOffset(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSourceOffset");

    UTargetingSelectionTask_Trace_GetSourceOffset_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSourceLocation
// Flags:  Native, Event, Protected, HasOutParms, HasDefaults, BlueprintEvent, Const
// RVA:    0x94247B0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   ReturnValue                  0x008(0x018), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
CoreUObject::FVector UTargetingSelectionTask_Trace::GetSourceLocation(const FTargetingRequestHandle& TargetingHandle) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetSourceLocation");

    UTargetingSelectionTask_Trace_GetSourceLocation_Params params {};
    params.TargetingHandle = TargetingHandle;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetAdditionalActorsToIgnore
// Flags:  Native, Event, Protected, HasOutParms, BlueprintEvent, Const
// RVA:    0x94244C0
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   OutAdditionalActorsToIgnore  0x008(0x010), Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic
void UTargetingSelectionTask_Trace::GetAdditionalActorsToIgnore(const FTargetingRequestHandle& TargetingHandle, BasicTypes::TArray<Engine::AActor*>& OutAdditionalActorsToIgnore) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.TargetingSelectionTask_Trace.GetAdditionalActorsToIgnore");

    UTargetingSelectionTask_Trace_GetAdditionalActorsToIgnore_Params params {};
    params.TargetingHandle = TargetingHandle;
    params.OutAdditionalActorsToIgnore = OutAdditionalActorsToIgnore;

    auto flags = fn->FunctionFlags;
    fn->FunctionFlags |= 0x400; // Native
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    OutAdditionalActorsToIgnore = params.OutAdditionalActorsToIgnore;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingSelectionTask_Trace.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingSelectionTask_Trace::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingSelectionTask_Trace");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingSortTask_Base.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingSortTask_Base::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingSortTask_Base");
    return ptr;
}

// Name:   Function /Script/TargetingSystem.SimpleTargetingFilterTask.BP_ShouldFilterTarget
// Flags:  Event, Public, HasOutParms, BlueprintEvent, Const
// RVA:    0x17D3880
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   TargetData                   0x008(0x110), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic
//   ReturnValue                  0x118(0x001), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
bool USimpleTargetingFilterTask::BP_ShouldFilterTarget(const FTargetingRequestHandle& TargetingHandle, const FTargetingDefaultResultData& TargetData) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.SimpleTargetingFilterTask.BP_ShouldFilterTarget");

    USimpleTargetingFilterTask_BP_ShouldFilterTarget_Params params {};
    params.TargetingHandle = TargetingHandle;
    params.TargetData = TargetData;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.SimpleTargetingFilterTask.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* USimpleTargetingFilterTask::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.SimpleTargetingFilterTask");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingFilterTask_ActorClass.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingFilterTask_ActorClass::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingFilterTask_ActorClass");
    return ptr;
}

// Name:   Function /Script/TargetingSystem.SimpleTargetingSortTask.BP_GetScoreForTarget
// Flags:  Event, Protected, HasOutParms, BlueprintEvent, Const
// RVA:    0x17D3880
// Params:
//   TargetingHandle              0x000(0x004), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic
//   TargetData                   0x008(0x110), Parm, ConstParm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic
//   ReturnValue                  0x118(0x004), Parm, OutParm, ReturnParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
float USimpleTargetingSortTask::BP_GetScoreForTarget(const FTargetingRequestHandle& TargetingHandle, const FTargetingDefaultResultData& TargetData) const
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Script/TargetingSystem.SimpleTargetingSortTask.BP_GetScoreForTarget");

    USimpleTargetingSortTask_BP_GetScoreForTarget_Params params {};
    params.TargetingHandle = TargetingHandle;
    params.TargetData = TargetData;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;

    return params.ReturnValue;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.SimpleTargetingSortTask.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* USimpleTargetingSortTask::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.SimpleTargetingSortTask");
    return ptr;
}

// Name:   PredefinedFunction Class /Script/TargetingSystem.TargetingFilterTask_SortByDistance.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTargetingFilterTask_SortByDistance::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("Class /Script/TargetingSystem.TargetingFilterTask_SortByDistance");
    return ptr;
}
}

