// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/Trait_CarrierBase_CLASSES.h"
#include "Headers/Trait_Carrier_Desert_CLASSES.h"
#include "Headers/Trait_Carrier_Desert_PARAMETERS.h"

namespace CG::Trait_Carrier_Desert
{
// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/GeneTraits/TraitBPs/Carrier/Scorched/Trait_Carrier_Desert.Trait_Carrier_Desert_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UTrait_Carrier_Desert_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/CoreBlueprints/GeneTraits/TraitBPs/Carrier/Scorched/Trait_Carrier_Desert.Trait_Carrier_Desert_C");
    return ptr;
}
}

