// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/CoreUObject_STRUCTS.h"
#include "Headers/Engine_CLASSES.h"
#include "Headers/Engine_STRUCTS.h"
#include "Headers/GeometryScriptingCore_STRUCTS.h"
#include "Headers/UDS_Island_CLASSES.h"
#include "Headers/UDS_Island_PARAMETERS.h"
#include "Headers/Ultra_Dynamic_Sky_CLASSES.h"

namespace CG::UDS_Island
{
// Name:   Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.AbsorptionColor
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void AUDS_Island_C::AbsorptionColor()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.AbsorptionColor");

    AUDS_Island_C_AbsorptionColor_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.UserConstructionScript
// Flags:  Event, Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void AUDS_Island_C::UserConstructionScript()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.UserConstructionScript");

    AUDS_Island_C_UserConstructionScript_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.ReceiveTick
// Flags:  Event, Public, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   DeltaSeconds                 0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void AUDS_Island_C::ReceiveTick(float DeltaSeconds)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.ReceiveTick");

    AUDS_Island_C_ReceiveTick_Params params {};
    params.DeltaSeconds = DeltaSeconds;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.ReceiveBeginPlay
// Flags:  Event, Protected, BlueprintEvent
// RVA:    0x17D3880
// Params:
void AUDS_Island_C::ReceiveBeginPlay()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.ReceiveBeginPlay");

    AUDS_Island_C_ReceiveBeginPlay_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.SequencerUpdate
// Flags:  BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
void AUDS_Island_C::SequencerUpdate()
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.SequencerUpdate");

    AUDS_Island_C_SequencerUpdate_Params params {};

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.ExecuteUbergraph_UDS_Island
// Flags:  Final, UberGraphFunction, HasDefaults
// RVA:    0x17D3880
// Params:
//   EntryPoint                   0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void AUDS_Island_C::ExecuteUbergraph_UDS_Island(int32_t EntryPoint)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.ExecuteUbergraph_UDS_Island");

    AUDS_Island_C_ExecuteUbergraph_UDS_Island_Params params {};
    params.EntryPoint = EntryPoint;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction BlueprintGeneratedClass /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* AUDS_Island_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/UltraDynamicSky/Blueprints/MapSpecific/UDS_Island.UDS_Island_C");
    return ptr;
}
}

