// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/BasicTypes_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/Engine_STRUCTS.h"
#include "Headers/ShooterGame_CLASSES.h"
#include "Headers/SlateCore_STRUCTS.h"
#include "Headers/UMG_CLASSES.h"
#include "Headers/W_SkillUpgradeEntry_CLASSES.h"
#include "Headers/W_SkillUpgradeEntry_PARAMETERS.h"

namespace CG::W_SkillUpgradeEntry
{
// Name:   Function /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C.DoTargetProgressOnBar
// Flags:  Public, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   DeltaTime                    0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   InputPin                     0x008(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash
//   Target                       0x010(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void UW_SkillUpgradeEntry_C::DoTargetProgressOnBar(double DeltaTime, UMG::UProgressBar* InputPin, double Target)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C.DoTargetProgressOnBar");

    UW_SkillUpgradeEntry_C_DoTargetProgressOnBar_Params params {};
    params.DeltaTime = DeltaTime;
    params.InputPin = InputPin;
    params.Target = Target;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C.UpdateUpgrade
// Flags:  Public, HasOutParms, HasDefaults, BlueprintCallable, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   ForSkill                     0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ConstParm, OutParm, ReferenceParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   CurrentRank                  0x008(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
//   ModifierName                 0x00C(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void UW_SkillUpgradeEntry_C::UpdateUpgrade(const BasicTypes::FName& ForSkill, int32_t CurrentRank, const BasicTypes::FName& ModifierName)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C.UpdateUpgrade");

    UW_SkillUpgradeEntry_C_UpdateUpgrade_Params params {};
    params.ForSkill = ForSkill;
    params.CurrentRank = CurrentRank;
    params.ModifierName = ModifierName;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C.Tick
// Flags:  BlueprintCosmetic, Event, Public, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   MyGeometry                   0x000(0x038), BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor
//   InDeltaTime                  0x038(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void UW_SkillUpgradeEntry_C::Tick(SlateCore::FGeometry MyGeometry, float InDeltaTime)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C.Tick");

    UW_SkillUpgradeEntry_C_Tick_Params params {};
    params.MyGeometry = MyGeometry;
    params.InDeltaTime = InDeltaTime;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C.ExecuteUbergraph_W_SkillUpgradeEntry
// Flags:  Final, UberGraphFunction, HasDefaults
// RVA:    0x17D3880
// Params:
//   EntryPoint                   0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void UW_SkillUpgradeEntry_C::ExecuteUbergraph_W_SkillUpgradeEntry(int32_t EntryPoint)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C.ExecuteUbergraph_W_SkillUpgradeEntry");

    UW_SkillUpgradeEntry_C_ExecuteUbergraph_W_SkillUpgradeEntry_Params params {};
    params.EntryPoint = EntryPoint;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction WidgetBlueprintGeneratedClass /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UW_SkillUpgradeEntry_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("WidgetBlueprintGeneratedClass /Game/ASA/UI/SkillTree/W_SkillUpgradeEntry.W_SkillUpgradeEntry_C");
    return ptr;
}
}

