// ----------------------------------------
// |        Generated By CheatGear        |
// ----------------------------------------
// | Game:    ARK Survival Ascended       |
// | Version: 5                           |
// | Date:    2026-02-22                  |
// ----------------------------------------

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/AIModule_CLASSES.h"
#include "Headers/CoreUObject_CLASSES.h"
#include "Headers/Engine_CLASSES.h"
#include "Headers/Engine_STRUCTS.h"
#include "Headers/WaitForWandering_DK_CLASSES.h"
#include "Headers/WaitForWandering_DK_PARAMETERS.h"

namespace CG::WaitForWandering_DK
{
// Name:   Function /Game/PrimalEarth/CoreAI/WaitForWandering_DK.WaitForWandering_DK_C.ReceiveConditionCheck
// Flags:  Event, Protected, BlueprintEvent
// RVA:    0x17D3880
// Params:
//   OwnerActor                   0x000(0x008), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash
void UWaitForWandering_DK_C::ReceiveConditionCheck(Engine::AActor* OwnerActor)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreAI/WaitForWandering_DK.WaitForWandering_DK_C.ReceiveConditionCheck");

    UWaitForWandering_DK_C_ReceiveConditionCheck_Params params {};
    params.OwnerActor = OwnerActor;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   Function /Game/PrimalEarth/CoreAI/WaitForWandering_DK.WaitForWandering_DK_C.ExecuteUbergraph_WaitForWandering_DK
// Flags:  Final, UberGraphFunction
// RVA:    0x17D3880
// Params:
//   EntryPoint                   0x000(0x004), BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
void UWaitForWandering_DK_C::ExecuteUbergraph_WaitForWandering_DK(int32_t EntryPoint)
{
    static CoreUObject::UFunction* fn = nullptr;
    if (!fn)
        fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/PrimalEarth/CoreAI/WaitForWandering_DK.WaitForWandering_DK_C.ExecuteUbergraph_WaitForWandering_DK");

    UWaitForWandering_DK_C_ExecuteUbergraph_WaitForWandering_DK_Params params {};
    params.EntryPoint = EntryPoint;

    auto flags = fn->FunctionFlags;
    CoreUObject::UObject::ProcessEvent(fn, &params);
    fn->FunctionFlags = flags;
}

// Name:   PredefinedFunction BlueprintGeneratedClass /Game/PrimalEarth/CoreAI/WaitForWandering_DK.WaitForWandering_DK_C.StaticClass
// Params:
//   ReturnValue                  0x000(0x000), 
CoreUObject::UClass* UWaitForWandering_DK_C::StaticClass()
{
    static CoreUObject::UClass* ptr = nullptr;
    if (!ptr)
        ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/PrimalEarth/CoreAI/WaitForWandering_DK.WaitForWandering_DK_C");
    return ptr;
}
}

